/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.api;

import com.google.gerrit.client.ApiCallback;
import com.google.gerrit.client.ApiClient;
import com.google.gerrit.client.ApiException;
import com.google.gerrit.client.ApiResponse;
import com.google.gerrit.client.Configuration;
import com.google.gerrit.client.Pair;
import com.google.gerrit.client.ProgressRequestBody;
import com.google.gerrit.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.io.File;
import com.google.gerrit.client.model.InstallPluginInput;
import com.google.gerrit.client.model.PluginInfo;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PluginsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PluginsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PluginsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deletePluginsPluginId
     * @param pluginId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePluginsPluginIdCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plugins/{plugin-id}"
            .replace("{" + "plugin-id" + "}", localVarApiClient.escapeString(pluginId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deletePluginsPluginIdValidateBeforeCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pluginId' is set
        if (pluginId == null) {
            throw new ApiException("Missing the required parameter 'pluginId' when calling deletePluginsPluginId(Async)");
        }

        return deletePluginsPluginIdCall(pluginId, _callback);

    }

    /**
     * Disable Plugin
     * Disables a plugin on the Gerrit server.
     * @param pluginId  (required)
     * @return PluginInfo
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PluginInfo deletePluginsPluginId(@javax.annotation.Nonnull String pluginId) throws ApiException {
        ApiResponse<PluginInfo> localVarResp = deletePluginsPluginIdWithHttpInfo(pluginId);
        return localVarResp.getData();
    }

    /**
     * Disable Plugin
     * Disables a plugin on the Gerrit server.
     * @param pluginId  (required)
     * @return ApiResponse&lt;PluginInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PluginInfo> deletePluginsPluginIdWithHttpInfo(@javax.annotation.Nonnull String pluginId) throws ApiException {
        okhttp3.Call localVarCall = deletePluginsPluginIdValidateBeforeCall(pluginId, null);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Disable Plugin (asynchronously)
     * Disables a plugin on the Gerrit server.
     * @param pluginId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePluginsPluginIdAsync(@javax.annotation.Nonnull String pluginId, final ApiCallback<PluginInfo> _callback) throws ApiException {

        okhttp3.Call localVarCall = deletePluginsPluginIdValidateBeforeCall(pluginId, _callback);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPlugins
     * @param all  (optional)
     * @param limit  (optional)
     * @param match  (optional)
     * @param prefix  (optional)
     * @param r  (optional)
     * @param start  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPluginsCall(@javax.annotation.Nullable Boolean all, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String match, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable String r, @javax.annotation.Nullable Integer start, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plugins";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (all != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("all", all));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (match != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("match", match));
        }

        if (prefix != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("prefix", prefix));
        }

        if (r != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("r", r));
        }

        if (start != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start", start));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPluginsValidateBeforeCall(@javax.annotation.Nullable Boolean all, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String match, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable String r, @javax.annotation.Nullable Integer start, final ApiCallback _callback) throws ApiException {
        return getPluginsCall(all, limit, match, prefix, r, start, _callback);

    }

    /**
     * List Plugins
     * Lists the plugins installed on the Gerrit server. Only the enabled plugins are returned unless the all option is specified.
     * @param all  (optional)
     * @param limit  (optional)
     * @param match  (optional)
     * @param prefix  (optional)
     * @param r  (optional)
     * @param start  (optional)
     * @return Map&lt;String, PluginInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Map<String, PluginInfo> getPlugins(@javax.annotation.Nullable Boolean all, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String match, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable String r, @javax.annotation.Nullable Integer start) throws ApiException {
        ApiResponse<Map<String, PluginInfo>> localVarResp = getPluginsWithHttpInfo(all, limit, match, prefix, r, start);
        return localVarResp.getData();
    }

    /**
     * List Plugins
     * Lists the plugins installed on the Gerrit server. Only the enabled plugins are returned unless the all option is specified.
     * @param all  (optional)
     * @param limit  (optional)
     * @param match  (optional)
     * @param prefix  (optional)
     * @param r  (optional)
     * @param start  (optional)
     * @return ApiResponse&lt;Map&lt;String, PluginInfo&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Map<String, PluginInfo>> getPluginsWithHttpInfo(@javax.annotation.Nullable Boolean all, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String match, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable String r, @javax.annotation.Nullable Integer start) throws ApiException {
        okhttp3.Call localVarCall = getPluginsValidateBeforeCall(all, limit, match, prefix, r, start, null);
        Type localVarReturnType = new TypeToken<Map<String, PluginInfo>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Plugins (asynchronously)
     * Lists the plugins installed on the Gerrit server. Only the enabled plugins are returned unless the all option is specified.
     * @param all  (optional)
     * @param limit  (optional)
     * @param match  (optional)
     * @param prefix  (optional)
     * @param r  (optional)
     * @param start  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPluginsAsync(@javax.annotation.Nullable Boolean all, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String match, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable String r, @javax.annotation.Nullable Integer start, final ApiCallback<Map<String, PluginInfo>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPluginsValidateBeforeCall(all, limit, match, prefix, r, start, _callback);
        Type localVarReturnType = new TypeToken<Map<String, PluginInfo>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPluginsPluginIdStatus
     * @param pluginId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPluginsPluginIdStatusCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plugins/{plugin-id}/status"
            .replace("{" + "plugin-id" + "}", localVarApiClient.escapeString(pluginId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPluginsPluginIdStatusValidateBeforeCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pluginId' is set
        if (pluginId == null) {
            throw new ApiException("Missing the required parameter 'pluginId' when calling getPluginsPluginIdStatus(Async)");
        }

        return getPluginsPluginIdStatusCall(pluginId, _callback);

    }

    /**
     * 
     * 
     * @param pluginId  (required)
     * @return PluginInfo
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PluginInfo getPluginsPluginIdStatus(@javax.annotation.Nonnull String pluginId) throws ApiException {
        ApiResponse<PluginInfo> localVarResp = getPluginsPluginIdStatusWithHttpInfo(pluginId);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param pluginId  (required)
     * @return ApiResponse&lt;PluginInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PluginInfo> getPluginsPluginIdStatusWithHttpInfo(@javax.annotation.Nonnull String pluginId) throws ApiException {
        okhttp3.Call localVarCall = getPluginsPluginIdStatusValidateBeforeCall(pluginId, null);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param pluginId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPluginsPluginIdStatusAsync(@javax.annotation.Nonnull String pluginId, final ApiCallback<PluginInfo> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPluginsPluginIdStatusValidateBeforeCall(pluginId, _callback);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postPluginsPluginIdDisable
     * @param pluginId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postPluginsPluginIdDisableCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plugins/{plugin-id}/disable"
            .replace("{" + "plugin-id" + "}", localVarApiClient.escapeString(pluginId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postPluginsPluginIdDisableValidateBeforeCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pluginId' is set
        if (pluginId == null) {
            throw new ApiException("Missing the required parameter 'pluginId' when calling postPluginsPluginIdDisable(Async)");
        }

        return postPluginsPluginIdDisableCall(pluginId, _callback);

    }

    /**
     * 
     * 
     * @param pluginId  (required)
     * @return PluginInfo
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PluginInfo postPluginsPluginIdDisable(@javax.annotation.Nonnull String pluginId) throws ApiException {
        ApiResponse<PluginInfo> localVarResp = postPluginsPluginIdDisableWithHttpInfo(pluginId);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param pluginId  (required)
     * @return ApiResponse&lt;PluginInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PluginInfo> postPluginsPluginIdDisableWithHttpInfo(@javax.annotation.Nonnull String pluginId) throws ApiException {
        okhttp3.Call localVarCall = postPluginsPluginIdDisableValidateBeforeCall(pluginId, null);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param pluginId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postPluginsPluginIdDisableAsync(@javax.annotation.Nonnull String pluginId, final ApiCallback<PluginInfo> _callback) throws ApiException {

        okhttp3.Call localVarCall = postPluginsPluginIdDisableValidateBeforeCall(pluginId, _callback);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postPluginsPluginIdEnable
     * @param pluginId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postPluginsPluginIdEnableCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plugins/{plugin-id}/enable"
            .replace("{" + "plugin-id" + "}", localVarApiClient.escapeString(pluginId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postPluginsPluginIdEnableValidateBeforeCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pluginId' is set
        if (pluginId == null) {
            throw new ApiException("Missing the required parameter 'pluginId' when calling postPluginsPluginIdEnable(Async)");
        }

        return postPluginsPluginIdEnableCall(pluginId, _callback);

    }

    /**
     * 
     * 
     * @param pluginId  (required)
     * @return PluginInfo
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PluginInfo postPluginsPluginIdEnable(@javax.annotation.Nonnull String pluginId) throws ApiException {
        ApiResponse<PluginInfo> localVarResp = postPluginsPluginIdEnableWithHttpInfo(pluginId);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param pluginId  (required)
     * @return ApiResponse&lt;PluginInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PluginInfo> postPluginsPluginIdEnableWithHttpInfo(@javax.annotation.Nonnull String pluginId) throws ApiException {
        okhttp3.Call localVarCall = postPluginsPluginIdEnableValidateBeforeCall(pluginId, null);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param pluginId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postPluginsPluginIdEnableAsync(@javax.annotation.Nonnull String pluginId, final ApiCallback<PluginInfo> _callback) throws ApiException {

        okhttp3.Call localVarCall = postPluginsPluginIdEnableValidateBeforeCall(pluginId, _callback);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postPluginsPluginIdReload
     * @param pluginId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postPluginsPluginIdReloadCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plugins/{plugin-id}/reload"
            .replace("{" + "plugin-id" + "}", localVarApiClient.escapeString(pluginId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postPluginsPluginIdReloadValidateBeforeCall(@javax.annotation.Nonnull String pluginId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pluginId' is set
        if (pluginId == null) {
            throw new ApiException("Missing the required parameter 'pluginId' when calling postPluginsPluginIdReload(Async)");
        }

        return postPluginsPluginIdReloadCall(pluginId, _callback);

    }

    /**
     * 
     * 
     * @param pluginId  (required)
     * @return PluginInfo
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PluginInfo postPluginsPluginIdReload(@javax.annotation.Nonnull String pluginId) throws ApiException {
        ApiResponse<PluginInfo> localVarResp = postPluginsPluginIdReloadWithHttpInfo(pluginId);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param pluginId  (required)
     * @return ApiResponse&lt;PluginInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PluginInfo> postPluginsPluginIdReloadWithHttpInfo(@javax.annotation.Nonnull String pluginId) throws ApiException {
        okhttp3.Call localVarCall = postPluginsPluginIdReloadValidateBeforeCall(pluginId, null);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param pluginId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postPluginsPluginIdReloadAsync(@javax.annotation.Nonnull String pluginId, final ApiCallback<PluginInfo> _callback) throws ApiException {

        okhttp3.Call localVarCall = postPluginsPluginIdReloadValidateBeforeCall(pluginId, _callback);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for putPluginsPluginId
     * @param pluginId  (required)
     * @param installPluginInput  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call putPluginsPluginIdCall(@javax.annotation.Nonnull String pluginId, @javax.annotation.Nullable InstallPluginInput installPluginInput, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = installPluginInput;

        // create path and map variables
        String localVarPath = "/plugins/{plugin-id}"
            .replace("{" + "plugin-id" + "}", localVarApiClient.escapeString(pluginId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/octet-stream"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call putPluginsPluginIdValidateBeforeCall(@javax.annotation.Nonnull String pluginId, @javax.annotation.Nullable InstallPluginInput installPluginInput, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pluginId' is set
        if (pluginId == null) {
            throw new ApiException("Missing the required parameter 'pluginId' when calling putPluginsPluginId(Async)");
        }

        return putPluginsPluginIdCall(pluginId, installPluginInput, _callback);

    }

    /**
     * Install Plugin
     * Installs a new plugin on the Gerrit server. If a plugin with the specified name already exists it is overwritten. Note: if the plugin provides its own name in the MANIFEST file, then the plugin name from the MANIFEST file has precedence over the \\{plugin-id\\} above.
     * @param pluginId  (required)
     * @param installPluginInput  (optional)
     * @return PluginInfo
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Response </td><td>  -  </td></tr>
     </table>
     */
    public PluginInfo putPluginsPluginId(@javax.annotation.Nonnull String pluginId, @javax.annotation.Nullable InstallPluginInput installPluginInput) throws ApiException {
        ApiResponse<PluginInfo> localVarResp = putPluginsPluginIdWithHttpInfo(pluginId, installPluginInput);
        return localVarResp.getData();
    }

    /**
     * Install Plugin
     * Installs a new plugin on the Gerrit server. If a plugin with the specified name already exists it is overwritten. Note: if the plugin provides its own name in the MANIFEST file, then the plugin name from the MANIFEST file has precedence over the \\{plugin-id\\} above.
     * @param pluginId  (required)
     * @param installPluginInput  (optional)
     * @return ApiResponse&lt;PluginInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PluginInfo> putPluginsPluginIdWithHttpInfo(@javax.annotation.Nonnull String pluginId, @javax.annotation.Nullable InstallPluginInput installPluginInput) throws ApiException {
        okhttp3.Call localVarCall = putPluginsPluginIdValidateBeforeCall(pluginId, installPluginInput, null);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Install Plugin (asynchronously)
     * Installs a new plugin on the Gerrit server. If a plugin with the specified name already exists it is overwritten. Note: if the plugin provides its own name in the MANIFEST file, then the plugin name from the MANIFEST file has precedence over the \\{plugin-id\\} above.
     * @param pluginId  (required)
     * @param installPluginInput  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call putPluginsPluginIdAsync(@javax.annotation.Nonnull String pluginId, @javax.annotation.Nullable InstallPluginInput installPluginInput, final ApiCallback<PluginInfo> _callback) throws ApiException {

        okhttp3.Call localVarCall = putPluginsPluginIdValidateBeforeCall(pluginId, installPluginInput, _callback);
        Type localVarReturnType = new TypeToken<PluginInfo>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
