/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gerrit.client.model.AccountInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * AttentionSetInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AttentionSetInfo {
  public static final String SERIALIZED_NAME_ACCOUNT = "account";
  @SerializedName(SERIALIZED_NAME_ACCOUNT)
  @javax.annotation.Nullable
  private AccountInfo account;

  public static final String SERIALIZED_NAME_LAST_UPDATE = "last_update";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATE)
  @javax.annotation.Nullable
  private String lastUpdate;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  @javax.annotation.Nullable
  private String reason;

  public static final String SERIALIZED_NAME_REASON_ACCOUNT = "reason_account";
  @SerializedName(SERIALIZED_NAME_REASON_ACCOUNT)
  @javax.annotation.Nullable
  private AccountInfo reasonAccount;

  public AttentionSetInfo() {
  }

  public AttentionSetInfo account(@javax.annotation.Nullable AccountInfo account) {
    this.account = account;
    return this;
  }

  /**
   * AccountInfo entity.
   * @return account
   */
  @javax.annotation.Nullable
  public AccountInfo getAccount() {
    return account;
  }

  public void setAccount(@javax.annotation.Nullable AccountInfo account) {
    this.account = account;
  }


  public AttentionSetInfo lastUpdate(@javax.annotation.Nullable String lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

  /**
   * The timestamp of the last update.
   * @return lastUpdate
   */
  @javax.annotation.Nullable
  public String getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(@javax.annotation.Nullable String lastUpdate) {
    this.lastUpdate = lastUpdate;
  }


  public AttentionSetInfo reason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * The reason for adding or removing the user. If the update was caused by another user, that account is represented by account ID in reason as &lt;GERRIT_ACCOUNT_18419&gt; and the corresponding AccountInfo can be found in reason_account field.
   * @return reason
   */
  @javax.annotation.Nullable
  public String getReason() {
    return reason;
  }

  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
  }


  public AttentionSetInfo reasonAccount(@javax.annotation.Nullable AccountInfo reasonAccount) {
    this.reasonAccount = reasonAccount;
    return this;
  }

  /**
   * AccountInfo of the user who caused the update.
   * @return reasonAccount
   */
  @javax.annotation.Nullable
  public AccountInfo getReasonAccount() {
    return reasonAccount;
  }

  public void setReasonAccount(@javax.annotation.Nullable AccountInfo reasonAccount) {
    this.reasonAccount = reasonAccount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttentionSetInfo attentionSetInfo = (AttentionSetInfo) o;
    return Objects.equals(this.account, attentionSetInfo.account) &&
        Objects.equals(this.lastUpdate, attentionSetInfo.lastUpdate) &&
        Objects.equals(this.reason, attentionSetInfo.reason) &&
        Objects.equals(this.reasonAccount, attentionSetInfo.reasonAccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, lastUpdate, reason, reasonAccount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttentionSetInfo {\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    reasonAccount: ").append(toIndentedString(reasonAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("account", "last_update", "reason", "reason_account"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AttentionSetInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AttentionSetInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AttentionSetInfo is not found in the empty JSON string", AttentionSetInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AttentionSetInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AttentionSetInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `account`
      if (jsonObj.get("account") != null && !jsonObj.get("account").isJsonNull()) {
        AccountInfo.validateJsonElement(jsonObj.get("account"));
      }
      if ((jsonObj.get("last_update") != null && !jsonObj.get("last_update").isJsonNull()) && !jsonObj.get("last_update").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `last_update` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_update").toString()));
      }
      if ((jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      // validate the optional field `reason_account`
      if (jsonObj.get("reason_account") != null && !jsonObj.get("reason_account").isJsonNull()) {
        AccountInfo.validateJsonElement(jsonObj.get("reason_account"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AttentionSetInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AttentionSetInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AttentionSetInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AttentionSetInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<AttentionSetInfo>() {
           @Override
           public void write(JsonWriter out, AttentionSetInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AttentionSetInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AttentionSetInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AttentionSetInfo
   * @throws IOException if the JSON string is invalid with respect to AttentionSetInfo
   */
  public static AttentionSetInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AttentionSetInfo.class);
  }

  /**
   * Convert an instance of AttentionSetInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

