/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * AutoCloseableChangesCheckInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-29T17:17:57.806085+02:00[Europe/Paris]", comments = "Generator version: 7.25.0")
public class AutoCloseableChangesCheckInput {
  public static final String SERIALIZED_NAME_FIX = "fix";
  @SerializedName(SERIALIZED_NAME_FIX)
  @javax.annotation.Nullable
  private Boolean fix;

  public static final String SERIALIZED_NAME_BRANCH = "branch";
  @SerializedName(SERIALIZED_NAME_BRANCH)
  @javax.annotation.Nullable
  private String branch;

  public static final String SERIALIZED_NAME_SKIP_COMMITS = "skip_commits";
  @SerializedName(SERIALIZED_NAME_SKIP_COMMITS)
  @javax.annotation.Nullable
  private Integer skipCommits;

  public static final String SERIALIZED_NAME_MAX_COMMITS = "max_commits";
  @SerializedName(SERIALIZED_NAME_MAX_COMMITS)
  @javax.annotation.Nullable
  private Integer maxCommits;

  public AutoCloseableChangesCheckInput() {
  }

  public AutoCloseableChangesCheckInput fix(@javax.annotation.Nullable Boolean fix) {
    this.fix = fix;
    return this;
  }

  /**
   * Get fix
   * @return fix
   */
  @javax.annotation.Nullable
  public Boolean getFix() {
    return fix;
  }

  public void setFix(@javax.annotation.Nullable Boolean fix) {
    this.fix = fix;
  }


  public AutoCloseableChangesCheckInput branch(@javax.annotation.Nullable String branch) {
    this.branch = branch;
    return this;
  }

  /**
   * Get branch
   * @return branch
   */
  @javax.annotation.Nullable
  public String getBranch() {
    return branch;
  }

  public void setBranch(@javax.annotation.Nullable String branch) {
    this.branch = branch;
  }


  public AutoCloseableChangesCheckInput skipCommits(@javax.annotation.Nullable Integer skipCommits) {
    this.skipCommits = skipCommits;
    return this;
  }

  /**
   * Get skipCommits
   * @return skipCommits
   */
  @javax.annotation.Nullable
  public Integer getSkipCommits() {
    return skipCommits;
  }

  public void setSkipCommits(@javax.annotation.Nullable Integer skipCommits) {
    this.skipCommits = skipCommits;
  }


  public AutoCloseableChangesCheckInput maxCommits(@javax.annotation.Nullable Integer maxCommits) {
    this.maxCommits = maxCommits;
    return this;
  }

  /**
   * Get maxCommits
   * @return maxCommits
   */
  @javax.annotation.Nullable
  public Integer getMaxCommits() {
    return maxCommits;
  }

  public void setMaxCommits(@javax.annotation.Nullable Integer maxCommits) {
    this.maxCommits = maxCommits;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoCloseableChangesCheckInput autoCloseableChangesCheckInput = (AutoCloseableChangesCheckInput) o;
    return Objects.equals(this.fix, autoCloseableChangesCheckInput.fix) &&
        Objects.equals(this.branch, autoCloseableChangesCheckInput.branch) &&
        Objects.equals(this.skipCommits, autoCloseableChangesCheckInput.skipCommits) &&
        Objects.equals(this.maxCommits, autoCloseableChangesCheckInput.maxCommits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fix, branch, skipCommits, maxCommits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoCloseableChangesCheckInput {\n");
    sb.append("    fix: ").append(toIndentedString(fix)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    skipCommits: ").append(toIndentedString(skipCommits)).append("\n");
    sb.append("    maxCommits: ").append(toIndentedString(maxCommits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("fix", "branch", "skip_commits", "max_commits"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AutoCloseableChangesCheckInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AutoCloseableChangesCheckInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AutoCloseableChangesCheckInput is not found in the empty JSON string", AutoCloseableChangesCheckInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AutoCloseableChangesCheckInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AutoCloseableChangesCheckInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("branch") != null && !jsonObj.get("branch").isJsonNull()) && !jsonObj.get("branch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `branch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("branch").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AutoCloseableChangesCheckInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AutoCloseableChangesCheckInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AutoCloseableChangesCheckInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AutoCloseableChangesCheckInput.class));

       return (TypeAdapter<T>) new TypeAdapter<AutoCloseableChangesCheckInput>() {
           @Override
           public void write(JsonWriter out, AutoCloseableChangesCheckInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AutoCloseableChangesCheckInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AutoCloseableChangesCheckInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AutoCloseableChangesCheckInput
   * @throws IOException if the JSON string is invalid with respect to AutoCloseableChangesCheckInput
   */
  public static AutoCloseableChangesCheckInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AutoCloseableChangesCheckInput.class);
  }

  /**
   * Convert an instance of AutoCloseableChangesCheckInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

