/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gerrit.client.model.SubmitRequirementInput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * BatchSubmitRequirementInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class BatchSubmitRequirementInput {
  public static final String SERIALIZED_NAME_COMMIT_MESSAGE = "commit_message";
  @SerializedName(SERIALIZED_NAME_COMMIT_MESSAGE)
  @javax.annotation.Nullable
  private String commitMessage;

  public static final String SERIALIZED_NAME_DELETE = "delete";
  @SerializedName(SERIALIZED_NAME_DELETE)
  @javax.annotation.Nullable
  private List<String> delete = new ArrayList<>();

  public static final String SERIALIZED_NAME_CREATE = "create";
  @SerializedName(SERIALIZED_NAME_CREATE)
  @javax.annotation.Nullable
  private List<SubmitRequirementInput> create = new ArrayList<>();

  public static final String SERIALIZED_NAME_UPDATE = "update";
  @SerializedName(SERIALIZED_NAME_UPDATE)
  @javax.annotation.Nullable
  private Map<String, SubmitRequirementInput> update = new HashMap<>();

  public BatchSubmitRequirementInput() {
  }

  public BatchSubmitRequirementInput commitMessage(@javax.annotation.Nullable String commitMessage) {
    this.commitMessage = commitMessage;
    return this;
  }

  /**
   * Message that should be used to commit the submit requirements updates in the project.config file to the refs/meta/config branch.
   * @return commitMessage
   */
  @javax.annotation.Nullable
  public String getCommitMessage() {
    return commitMessage;
  }

  public void setCommitMessage(@javax.annotation.Nullable String commitMessage) {
    this.commitMessage = commitMessage;
  }


  public BatchSubmitRequirementInput delete(@javax.annotation.Nullable List<String> delete) {
    this.delete = delete;
    return this;
  }

  public BatchSubmitRequirementInput addDeleteItem(String deleteItem) {
    if (this.delete == null) {
      this.delete = new ArrayList<>();
    }
    this.delete.add(deleteItem);
    return this;
  }

  /**
   * List of submit requirements that should be deleted.
   * @return delete
   */
  @javax.annotation.Nullable
  public List<String> getDelete() {
    return delete;
  }

  public void setDelete(@javax.annotation.Nullable List<String> delete) {
    this.delete = delete;
  }


  public BatchSubmitRequirementInput create(@javax.annotation.Nullable List<SubmitRequirementInput> create) {
    this.create = create;
    return this;
  }

  public BatchSubmitRequirementInput addCreateItem(SubmitRequirementInput createItem) {
    if (this.create == null) {
      this.create = new ArrayList<>();
    }
    this.create.add(createItem);
    return this;
  }

  /**
   * List of SubmitRequirementInput entities that describe submit requirements that should be created.
   * @return create
   */
  @javax.annotation.Nullable
  public List<SubmitRequirementInput> getCreate() {
    return create;
  }

  public void setCreate(@javax.annotation.Nullable List<SubmitRequirementInput> create) {
    this.create = create;
  }


  public BatchSubmitRequirementInput update(@javax.annotation.Nullable Map<String, SubmitRequirementInput> update) {
    this.update = update;
    return this;
  }

  public BatchSubmitRequirementInput putUpdateItem(String key, SubmitRequirementInput updateItem) {
    if (this.update == null) {
      this.update = new HashMap<>();
    }
    this.update.put(key, updateItem);
    return this;
  }

  /**
   * Map of submit requirement names to SubmitRequirementInput entities that describe the updates that should be done for the submit requirements. The given inputs must set all properties (including those that are not being changed).
   * @return update
   */
  @javax.annotation.Nullable
  public Map<String, SubmitRequirementInput> getUpdate() {
    return update;
  }

  public void setUpdate(@javax.annotation.Nullable Map<String, SubmitRequirementInput> update) {
    this.update = update;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchSubmitRequirementInput batchSubmitRequirementInput = (BatchSubmitRequirementInput) o;
    return Objects.equals(this.commitMessage, batchSubmitRequirementInput.commitMessage) &&
        Objects.equals(this.delete, batchSubmitRequirementInput.delete) &&
        Objects.equals(this.create, batchSubmitRequirementInput.create) &&
        Objects.equals(this.update, batchSubmitRequirementInput.update);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commitMessage, delete, create, update);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchSubmitRequirementInput {\n");
    sb.append("    commitMessage: ").append(toIndentedString(commitMessage)).append("\n");
    sb.append("    delete: ").append(toIndentedString(delete)).append("\n");
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("    update: ").append(toIndentedString(update)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("commit_message", "delete", "create", "update"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BatchSubmitRequirementInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchSubmitRequirementInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BatchSubmitRequirementInput is not found in the empty JSON string", BatchSubmitRequirementInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BatchSubmitRequirementInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BatchSubmitRequirementInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("commit_message") != null && !jsonObj.get("commit_message").isJsonNull()) && !jsonObj.get("commit_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `commit_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("commit_message").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("delete") != null && !jsonObj.get("delete").isJsonNull() && !jsonObj.get("delete").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `delete` to be an array in the JSON string but got `%s`", jsonObj.get("delete").toString()));
      }
      if (jsonObj.get("create") != null && !jsonObj.get("create").isJsonNull()) {
        JsonArray jsonArraycreate = jsonObj.getAsJsonArray("create");
        if (jsonArraycreate != null) {
          // ensure the json data is an array
          if (!jsonObj.get("create").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `create` to be an array in the JSON string but got `%s`", jsonObj.get("create").toString()));
          }

          // validate the optional field `create` (array)
          for (int i = 0; i < jsonArraycreate.size(); i++) {
            SubmitRequirementInput.validateJsonElement(jsonArraycreate.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchSubmitRequirementInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchSubmitRequirementInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchSubmitRequirementInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchSubmitRequirementInput.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchSubmitRequirementInput>() {
           @Override
           public void write(JsonWriter out, BatchSubmitRequirementInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchSubmitRequirementInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BatchSubmitRequirementInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BatchSubmitRequirementInput
   * @throws IOException if the JSON string is invalid with respect to BatchSubmitRequirementInput
   */
  public static BatchSubmitRequirementInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchSubmitRequirementInput.class);
  }

  /**
   * Convert an instance of BatchSubmitRequirementInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

