/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * CommitMessageInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class CommitMessageInfo {
  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  @javax.annotation.Nullable
  private String subject;

  public static final String SERIALIZED_NAME_FULL_MESSAGE = "full_message";
  @SerializedName(SERIALIZED_NAME_FULL_MESSAGE)
  @javax.annotation.Nullable
  private String fullMessage;

  public static final String SERIALIZED_NAME_FOOTERS = "footers";
  @SerializedName(SERIALIZED_NAME_FOOTERS)
  @javax.annotation.Nullable
  private Map<String, String> footers = new HashMap<>();

  public CommitMessageInfo() {
  }

  public CommitMessageInfo subject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @javax.annotation.Nullable
  public String getSubject() {
    return subject;
  }

  public void setSubject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
  }


  public CommitMessageInfo fullMessage(@javax.annotation.Nullable String fullMessage) {
    this.fullMessage = fullMessage;
    return this;
  }

  /**
   * Get fullMessage
   * @return fullMessage
   */
  @javax.annotation.Nullable
  public String getFullMessage() {
    return fullMessage;
  }

  public void setFullMessage(@javax.annotation.Nullable String fullMessage) {
    this.fullMessage = fullMessage;
  }


  public CommitMessageInfo footers(@javax.annotation.Nullable Map<String, String> footers) {
    this.footers = footers;
    return this;
  }

  public CommitMessageInfo putFootersItem(String key, String footersItem) {
    if (this.footers == null) {
      this.footers = new HashMap<>();
    }
    this.footers.put(key, footersItem);
    return this;
  }

  /**
   * Get footers
   * @return footers
   */
  @javax.annotation.Nullable
  public Map<String, String> getFooters() {
    return footers;
  }

  public void setFooters(@javax.annotation.Nullable Map<String, String> footers) {
    this.footers = footers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitMessageInfo commitMessageInfo = (CommitMessageInfo) o;
    return Objects.equals(this.subject, commitMessageInfo.subject) &&
        Objects.equals(this.fullMessage, commitMessageInfo.fullMessage) &&
        Objects.equals(this.footers, commitMessageInfo.footers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subject, fullMessage, footers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitMessageInfo {\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    fullMessage: ").append(toIndentedString(fullMessage)).append("\n");
    sb.append("    footers: ").append(toIndentedString(footers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("subject", "full_message", "footers"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CommitMessageInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CommitMessageInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CommitMessageInfo is not found in the empty JSON string", CommitMessageInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CommitMessageInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CommitMessageInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("subject") != null && !jsonObj.get("subject").isJsonNull()) && !jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if ((jsonObj.get("full_message") != null && !jsonObj.get("full_message").isJsonNull()) && !jsonObj.get("full_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `full_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("full_message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommitMessageInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommitMessageInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommitMessageInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommitMessageInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<CommitMessageInfo>() {
           @Override
           public void write(JsonWriter out, CommitMessageInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommitMessageInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CommitMessageInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CommitMessageInfo
   * @throws IOException if the JSON string is invalid with respect to CommitMessageInfo
   */
  public static CommitMessageInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommitMessageInfo.class);
  }

  /**
   * Convert an instance of CommitMessageInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

