/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gerrit.client.model.NotifyHandling;
import com.google.gerrit.client.model.NotifyInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * CommitMessageInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class CommitMessageInput {
  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public static final String SERIALIZED_NAME_NOTIFY = "notify";
  @SerializedName(SERIALIZED_NAME_NOTIFY)
  @javax.annotation.Nullable
  private NotifyHandling notify;

  public static final String SERIALIZED_NAME_NOTIFY_DETAILS = "notify_details";
  @SerializedName(SERIALIZED_NAME_NOTIFY_DETAILS)
  @javax.annotation.Nullable
  private Map<String, NotifyInfo> notifyDetails = new HashMap<>();

  public static final String SERIALIZED_NAME_COMMITTER_EMAIL = "committer_email";
  @SerializedName(SERIALIZED_NAME_COMMITTER_EMAIL)
  @javax.annotation.Nullable
  private String committerEmail;

  public CommitMessageInput() {
  }

  public CommitMessageInput message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * New commit message.
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }


  public CommitMessageInput notify(@javax.annotation.Nullable NotifyHandling notify) {
    this.notify = notify;
    return this;
  }

  /**
   * Notify handling that defines to whom email notifications should be sent after the commit message was updated. + Allowed values are NONE, OWNER, OWNER_REVIEWERS and ALL. + If not set, the default is OWNER for WIP changes and ALL otherwise.
   * @return notify
   */
  @javax.annotation.Nullable
  public NotifyHandling getNotify() {
    return notify;
  }

  public void setNotify(@javax.annotation.Nullable NotifyHandling notify) {
    this.notify = notify;
  }


  public CommitMessageInput notifyDetails(@javax.annotation.Nullable Map<String, NotifyInfo> notifyDetails) {
    this.notifyDetails = notifyDetails;
    return this;
  }

  public CommitMessageInput putNotifyDetailsItem(String key, NotifyInfo notifyDetailsItem) {
    if (this.notifyDetails == null) {
      this.notifyDetails = new HashMap<>();
    }
    this.notifyDetails.put(key, notifyDetailsItem);
    return this;
  }

  /**
   * Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity.
   * @return notifyDetails
   */
  @javax.annotation.Nullable
  public Map<String, NotifyInfo> getNotifyDetails() {
    return notifyDetails;
  }

  public void setNotifyDetails(@javax.annotation.Nullable Map<String, NotifyInfo> notifyDetails) {
    this.notifyDetails = notifyDetails;
  }


  public CommitMessageInput committerEmail(@javax.annotation.Nullable String committerEmail) {
    this.committerEmail = committerEmail;
    return this;
  }

  /**
   * New message is committed using this email address. Only the registered emails of the calling user are considered valid.
   * @return committerEmail
   */
  @javax.annotation.Nullable
  public String getCommitterEmail() {
    return committerEmail;
  }

  public void setCommitterEmail(@javax.annotation.Nullable String committerEmail) {
    this.committerEmail = committerEmail;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitMessageInput commitMessageInput = (CommitMessageInput) o;
    return Objects.equals(this.message, commitMessageInput.message) &&
        Objects.equals(this.notify, commitMessageInput.notify) &&
        Objects.equals(this.notifyDetails, commitMessageInput.notifyDetails) &&
        Objects.equals(this.committerEmail, commitMessageInput.committerEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, notify, notifyDetails, committerEmail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitMessageInput {\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    notify: ").append(toIndentedString(notify)).append("\n");
    sb.append("    notifyDetails: ").append(toIndentedString(notifyDetails)).append("\n");
    sb.append("    committerEmail: ").append(toIndentedString(committerEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("message", "notify", "notify_details", "committer_email"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CommitMessageInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CommitMessageInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CommitMessageInput is not found in the empty JSON string", CommitMessageInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CommitMessageInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CommitMessageInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      // validate the optional field `notify`
      if (jsonObj.get("notify") != null && !jsonObj.get("notify").isJsonNull()) {
        NotifyHandling.validateJsonElement(jsonObj.get("notify"));
      }
      if ((jsonObj.get("committer_email") != null && !jsonObj.get("committer_email").isJsonNull()) && !jsonObj.get("committer_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `committer_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("committer_email").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommitMessageInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommitMessageInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommitMessageInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommitMessageInput.class));

       return (TypeAdapter<T>) new TypeAdapter<CommitMessageInput>() {
           @Override
           public void write(JsonWriter out, CommitMessageInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommitMessageInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CommitMessageInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CommitMessageInput
   * @throws IOException if the JSON string is invalid with respect to CommitMessageInput
   */
  public static CommitMessageInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommitMessageInput.class);
  }

  /**
   * Convert an instance of CommitMessageInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

