/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * ConfigUpdateEntryInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ConfigUpdateEntryInfo {
  public static final String SERIALIZED_NAME_CONFIG_KEY = "config_key";
  @SerializedName(SERIALIZED_NAME_CONFIG_KEY)
  @javax.annotation.Nullable
  private String configKey;

  public static final String SERIALIZED_NAME_OLD_VALUE = "old_value";
  @SerializedName(SERIALIZED_NAME_OLD_VALUE)
  @javax.annotation.Nullable
  private String oldValue;

  public static final String SERIALIZED_NAME_NEW_VALUE = "new_value";
  @SerializedName(SERIALIZED_NAME_NEW_VALUE)
  @javax.annotation.Nullable
  private String newValue;

  public ConfigUpdateEntryInfo() {
  }

  public ConfigUpdateEntryInfo configKey(@javax.annotation.Nullable String configKey) {
    this.configKey = configKey;
    return this;
  }

  /**
   * The config key that contains the value.
   * @return configKey
   */
  @javax.annotation.Nullable
  public String getConfigKey() {
    return configKey;
  }

  public void setConfigKey(@javax.annotation.Nullable String configKey) {
    this.configKey = configKey;
  }


  public ConfigUpdateEntryInfo oldValue(@javax.annotation.Nullable String oldValue) {
    this.oldValue = oldValue;
    return this;
  }

  /**
   * The old config value. + Missing if value was not previously configured.
   * @return oldValue
   */
  @javax.annotation.Nullable
  public String getOldValue() {
    return oldValue;
  }

  public void setOldValue(@javax.annotation.Nullable String oldValue) {
    this.oldValue = oldValue;
  }


  public ConfigUpdateEntryInfo newValue(@javax.annotation.Nullable String newValue) {
    this.newValue = newValue;
    return this;
  }

  /**
   * The new config value, picked up after reload.
   * @return newValue
   */
  @javax.annotation.Nullable
  public String getNewValue() {
    return newValue;
  }

  public void setNewValue(@javax.annotation.Nullable String newValue) {
    this.newValue = newValue;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigUpdateEntryInfo configUpdateEntryInfo = (ConfigUpdateEntryInfo) o;
    return Objects.equals(this.configKey, configUpdateEntryInfo.configKey) &&
        Objects.equals(this.oldValue, configUpdateEntryInfo.oldValue) &&
        Objects.equals(this.newValue, configUpdateEntryInfo.newValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configKey, oldValue, newValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigUpdateEntryInfo {\n");
    sb.append("    configKey: ").append(toIndentedString(configKey)).append("\n");
    sb.append("    oldValue: ").append(toIndentedString(oldValue)).append("\n");
    sb.append("    newValue: ").append(toIndentedString(newValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("config_key", "old_value", "new_value"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConfigUpdateEntryInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConfigUpdateEntryInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ConfigUpdateEntryInfo is not found in the empty JSON string", ConfigUpdateEntryInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConfigUpdateEntryInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ConfigUpdateEntryInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("config_key") != null && !jsonObj.get("config_key").isJsonNull()) && !jsonObj.get("config_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `config_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("config_key").toString()));
      }
      if ((jsonObj.get("old_value") != null && !jsonObj.get("old_value").isJsonNull()) && !jsonObj.get("old_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `old_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("old_value").toString()));
      }
      if ((jsonObj.get("new_value") != null && !jsonObj.get("new_value").isJsonNull()) && !jsonObj.get("new_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `new_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("new_value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConfigUpdateEntryInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConfigUpdateEntryInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConfigUpdateEntryInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConfigUpdateEntryInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<ConfigUpdateEntryInfo>() {
           @Override
           public void write(JsonWriter out, ConfigUpdateEntryInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConfigUpdateEntryInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConfigUpdateEntryInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConfigUpdateEntryInfo
   * @throws IOException if the JSON string is invalid with respect to ConfigUpdateEntryInfo
   */
  public static ConfigUpdateEntryInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConfigUpdateEntryInfo.class);
  }

  /**
   * Convert an instance of ConfigUpdateEntryInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

