/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * ConsistencyCheckInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ConsistencyCheckInput {
  public static final String SERIALIZED_NAME_CHECK_ACCOUNTS = "check_accounts";
  @SerializedName(SERIALIZED_NAME_CHECK_ACCOUNTS)
  @javax.annotation.Nullable
  private Object checkAccounts;

  public static final String SERIALIZED_NAME_CHECK_ACCOUNT_EXTERNAL_IDS = "check_account_external_ids";
  @SerializedName(SERIALIZED_NAME_CHECK_ACCOUNT_EXTERNAL_IDS)
  @javax.annotation.Nullable
  private Object checkAccountExternalIds;

  public static final String SERIALIZED_NAME_CHECK_GROUPS = "check_groups";
  @SerializedName(SERIALIZED_NAME_CHECK_GROUPS)
  @javax.annotation.Nullable
  private Object checkGroups;

  public ConsistencyCheckInput() {
  }

  public ConsistencyCheckInput checkAccounts(@javax.annotation.Nullable Object checkAccounts) {
    this.checkAccounts = checkAccounts;
    return this;
  }

  /**
   * Get checkAccounts
   * @return checkAccounts
   */
  @javax.annotation.Nullable
  public Object getCheckAccounts() {
    return checkAccounts;
  }

  public void setCheckAccounts(@javax.annotation.Nullable Object checkAccounts) {
    this.checkAccounts = checkAccounts;
  }


  public ConsistencyCheckInput checkAccountExternalIds(@javax.annotation.Nullable Object checkAccountExternalIds) {
    this.checkAccountExternalIds = checkAccountExternalIds;
    return this;
  }

  /**
   * Get checkAccountExternalIds
   * @return checkAccountExternalIds
   */
  @javax.annotation.Nullable
  public Object getCheckAccountExternalIds() {
    return checkAccountExternalIds;
  }

  public void setCheckAccountExternalIds(@javax.annotation.Nullable Object checkAccountExternalIds) {
    this.checkAccountExternalIds = checkAccountExternalIds;
  }


  public ConsistencyCheckInput checkGroups(@javax.annotation.Nullable Object checkGroups) {
    this.checkGroups = checkGroups;
    return this;
  }

  /**
   * Get checkGroups
   * @return checkGroups
   */
  @javax.annotation.Nullable
  public Object getCheckGroups() {
    return checkGroups;
  }

  public void setCheckGroups(@javax.annotation.Nullable Object checkGroups) {
    this.checkGroups = checkGroups;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsistencyCheckInput consistencyCheckInput = (ConsistencyCheckInput) o;
    return Objects.equals(this.checkAccounts, consistencyCheckInput.checkAccounts) &&
        Objects.equals(this.checkAccountExternalIds, consistencyCheckInput.checkAccountExternalIds) &&
        Objects.equals(this.checkGroups, consistencyCheckInput.checkGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkAccounts, checkAccountExternalIds, checkGroups);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsistencyCheckInput {\n");
    sb.append("    checkAccounts: ").append(toIndentedString(checkAccounts)).append("\n");
    sb.append("    checkAccountExternalIds: ").append(toIndentedString(checkAccountExternalIds)).append("\n");
    sb.append("    checkGroups: ").append(toIndentedString(checkGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("check_accounts", "check_account_external_ids", "check_groups"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConsistencyCheckInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConsistencyCheckInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ConsistencyCheckInput is not found in the empty JSON string", ConsistencyCheckInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConsistencyCheckInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ConsistencyCheckInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConsistencyCheckInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConsistencyCheckInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConsistencyCheckInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConsistencyCheckInput.class));

       return (TypeAdapter<T>) new TypeAdapter<ConsistencyCheckInput>() {
           @Override
           public void write(JsonWriter out, ConsistencyCheckInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConsistencyCheckInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConsistencyCheckInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConsistencyCheckInput
   * @throws IOException if the JSON string is invalid with respect to ConsistencyCheckInput
   */
  public static ConsistencyCheckInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConsistencyCheckInput.class);
  }

  /**
   * Convert an instance of ConsistencyCheckInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

