/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * ContentEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-29T17:17:57.806085+02:00[Europe/Paris]", comments = "Generator version: 7.25.0")
public class ContentEntry {
  public static final String SERIALIZED_NAME_AB = "ab";
  @SerializedName(SERIALIZED_NAME_AB)
  @javax.annotation.Nullable
  private List<String> ab = new ArrayList<>();

  public static final String SERIALIZED_NAME_A = "a";
  @SerializedName(SERIALIZED_NAME_A)
  @javax.annotation.Nullable
  private List<String> a = new ArrayList<>();

  public static final String SERIALIZED_NAME_B = "b";
  @SerializedName(SERIALIZED_NAME_B)
  @javax.annotation.Nullable
  private List<String> b = new ArrayList<>();

  public static final String SERIALIZED_NAME_EDIT_A = "edit_a";
  @SerializedName(SERIALIZED_NAME_EDIT_A)
  @javax.annotation.Nullable
  private List<List<Integer>> editA = new ArrayList<>();

  public static final String SERIALIZED_NAME_EDIT_B = "edit_b";
  @SerializedName(SERIALIZED_NAME_EDIT_B)
  @javax.annotation.Nullable
  private List<List<Integer>> editB = new ArrayList<>();

  public static final String SERIALIZED_NAME_DUE_TO_REBASE = "due_to_rebase";
  @SerializedName(SERIALIZED_NAME_DUE_TO_REBASE)
  @javax.annotation.Nullable
  private Boolean dueToRebase;

  public static final String SERIALIZED_NAME_COMMON = "common";
  @SerializedName(SERIALIZED_NAME_COMMON)
  @javax.annotation.Nullable
  private Boolean common;

  public static final String SERIALIZED_NAME_SKIP = "skip";
  @SerializedName(SERIALIZED_NAME_SKIP)
  @javax.annotation.Nullable
  private Integer skip;

  public ContentEntry() {
  }

  public ContentEntry ab(@javax.annotation.Nullable List<String> ab) {
    this.ab = ab;
    return this;
  }

  public ContentEntry addAbItem(String abItem) {
    if (this.ab == null) {
      this.ab = new ArrayList<>();
    }
    this.ab.add(abItem);
    return this;
  }

  /**
   * Get ab
   * @return ab
   */
  @javax.annotation.Nullable
  public List<String> getAb() {
    return ab;
  }

  public void setAb(@javax.annotation.Nullable List<String> ab) {
    this.ab = ab;
  }


  public ContentEntry a(@javax.annotation.Nullable List<String> a) {
    this.a = a;
    return this;
  }

  public ContentEntry addAItem(String aItem) {
    if (this.a == null) {
      this.a = new ArrayList<>();
    }
    this.a.add(aItem);
    return this;
  }

  /**
   * Get a
   * @return a
   */
  @javax.annotation.Nullable
  public List<String> getA() {
    return a;
  }

  public void setA(@javax.annotation.Nullable List<String> a) {
    this.a = a;
  }


  public ContentEntry b(@javax.annotation.Nullable List<String> b) {
    this.b = b;
    return this;
  }

  public ContentEntry addBItem(String bItem) {
    if (this.b == null) {
      this.b = new ArrayList<>();
    }
    this.b.add(bItem);
    return this;
  }

  /**
   * Get b
   * @return b
   */
  @javax.annotation.Nullable
  public List<String> getB() {
    return b;
  }

  public void setB(@javax.annotation.Nullable List<String> b) {
    this.b = b;
  }


  public ContentEntry editA(@javax.annotation.Nullable List<List<Integer>> editA) {
    this.editA = editA;
    return this;
  }

  public ContentEntry addEditAItem(List<Integer> editAItem) {
    if (this.editA == null) {
      this.editA = new ArrayList<>();
    }
    this.editA.add(editAItem);
    return this;
  }

  /**
   * Get editA
   * @return editA
   */
  @javax.annotation.Nullable
  public List<List<Integer>> getEditA() {
    return editA;
  }

  public void setEditA(@javax.annotation.Nullable List<List<Integer>> editA) {
    this.editA = editA;
  }


  public ContentEntry editB(@javax.annotation.Nullable List<List<Integer>> editB) {
    this.editB = editB;
    return this;
  }

  public ContentEntry addEditBItem(List<Integer> editBItem) {
    if (this.editB == null) {
      this.editB = new ArrayList<>();
    }
    this.editB.add(editBItem);
    return this;
  }

  /**
   * Get editB
   * @return editB
   */
  @javax.annotation.Nullable
  public List<List<Integer>> getEditB() {
    return editB;
  }

  public void setEditB(@javax.annotation.Nullable List<List<Integer>> editB) {
    this.editB = editB;
  }


  public ContentEntry dueToRebase(@javax.annotation.Nullable Boolean dueToRebase) {
    this.dueToRebase = dueToRebase;
    return this;
  }

  /**
   * Get dueToRebase
   * @return dueToRebase
   */
  @javax.annotation.Nullable
  public Boolean getDueToRebase() {
    return dueToRebase;
  }

  public void setDueToRebase(@javax.annotation.Nullable Boolean dueToRebase) {
    this.dueToRebase = dueToRebase;
  }


  public ContentEntry common(@javax.annotation.Nullable Boolean common) {
    this.common = common;
    return this;
  }

  /**
   * Get common
   * @return common
   */
  @javax.annotation.Nullable
  public Boolean getCommon() {
    return common;
  }

  public void setCommon(@javax.annotation.Nullable Boolean common) {
    this.common = common;
  }


  public ContentEntry skip(@javax.annotation.Nullable Integer skip) {
    this.skip = skip;
    return this;
  }

  /**
   * Get skip
   * @return skip
   */
  @javax.annotation.Nullable
  public Integer getSkip() {
    return skip;
  }

  public void setSkip(@javax.annotation.Nullable Integer skip) {
    this.skip = skip;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentEntry contentEntry = (ContentEntry) o;
    return Objects.equals(this.ab, contentEntry.ab) &&
        Objects.equals(this.a, contentEntry.a) &&
        Objects.equals(this.b, contentEntry.b) &&
        Objects.equals(this.editA, contentEntry.editA) &&
        Objects.equals(this.editB, contentEntry.editB) &&
        Objects.equals(this.dueToRebase, contentEntry.dueToRebase) &&
        Objects.equals(this.common, contentEntry.common) &&
        Objects.equals(this.skip, contentEntry.skip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ab, a, b, editA, editB, dueToRebase, common, skip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentEntry {\n");
    sb.append("    ab: ").append(toIndentedString(ab)).append("\n");
    sb.append("    a: ").append(toIndentedString(a)).append("\n");
    sb.append("    b: ").append(toIndentedString(b)).append("\n");
    sb.append("    editA: ").append(toIndentedString(editA)).append("\n");
    sb.append("    editB: ").append(toIndentedString(editB)).append("\n");
    sb.append("    dueToRebase: ").append(toIndentedString(dueToRebase)).append("\n");
    sb.append("    common: ").append(toIndentedString(common)).append("\n");
    sb.append("    skip: ").append(toIndentedString(skip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("ab", "a", "b", "edit_a", "edit_b", "due_to_rebase", "common", "skip"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ContentEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ContentEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ContentEntry is not found in the empty JSON string", ContentEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ContentEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ContentEntry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("ab") != null && !jsonObj.get("ab").isJsonNull() && !jsonObj.get("ab").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ab` to be an array in the JSON string but got `%s`", jsonObj.get("ab").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("a") != null && !jsonObj.get("a").isJsonNull() && !jsonObj.get("a").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `a` to be an array in the JSON string but got `%s`", jsonObj.get("a").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("b") != null && !jsonObj.get("b").isJsonNull() && !jsonObj.get("b").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `b` to be an array in the JSON string but got `%s`", jsonObj.get("b").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("edit_a") != null && !jsonObj.get("edit_a").isJsonNull() && !jsonObj.get("edit_a").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `edit_a` to be an array in the JSON string but got `%s`", jsonObj.get("edit_a").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("edit_b") != null && !jsonObj.get("edit_b").isJsonNull() && !jsonObj.get("edit_b").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `edit_b` to be an array in the JSON string but got `%s`", jsonObj.get("edit_b").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContentEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContentEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContentEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContentEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<ContentEntry>() {
           @Override
           public void write(JsonWriter out, ContentEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContentEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ContentEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ContentEntry
   * @throws IOException if the JSON string is invalid with respect to ContentEntry
   */
  public static ContentEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContentEntry.class);
  }

  /**
   * Convert an instance of ContentEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

