/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * EditPreferencesInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class EditPreferencesInfo {
  public static final String SERIALIZED_NAME_TAB_SIZE = "tab_size";
  @SerializedName(SERIALIZED_NAME_TAB_SIZE)
  @javax.annotation.Nullable
  private Integer tabSize;

  public static final String SERIALIZED_NAME_LINE_LENGTH = "line_length";
  @SerializedName(SERIALIZED_NAME_LINE_LENGTH)
  @javax.annotation.Nullable
  private Integer lineLength;

  public static final String SERIALIZED_NAME_INDENT_UNIT = "indent_unit";
  @SerializedName(SERIALIZED_NAME_INDENT_UNIT)
  @javax.annotation.Nullable
  private Integer indentUnit;

  public static final String SERIALIZED_NAME_CURSOR_BLINK_RATE = "cursor_blink_rate";
  @SerializedName(SERIALIZED_NAME_CURSOR_BLINK_RATE)
  @javax.annotation.Nullable
  private Integer cursorBlinkRate;

  public static final String SERIALIZED_NAME_HIDE_TOP_MENU = "hide_top_menu";
  @SerializedName(SERIALIZED_NAME_HIDE_TOP_MENU)
  @javax.annotation.Nullable
  private Boolean hideTopMenu;

  public static final String SERIALIZED_NAME_SHOW_TABS = "show_tabs";
  @SerializedName(SERIALIZED_NAME_SHOW_TABS)
  @javax.annotation.Nullable
  private Boolean showTabs;

  public static final String SERIALIZED_NAME_SHOW_WHITESPACE_ERRORS = "show_whitespace_errors";
  @SerializedName(SERIALIZED_NAME_SHOW_WHITESPACE_ERRORS)
  @javax.annotation.Nullable
  private Boolean showWhitespaceErrors;

  public static final String SERIALIZED_NAME_SYNTAX_HIGHLIGHTING = "syntax_highlighting";
  @SerializedName(SERIALIZED_NAME_SYNTAX_HIGHLIGHTING)
  @javax.annotation.Nullable
  private Boolean syntaxHighlighting;

  public static final String SERIALIZED_NAME_HIDE_LINE_NUMBERS = "hide_line_numbers";
  @SerializedName(SERIALIZED_NAME_HIDE_LINE_NUMBERS)
  @javax.annotation.Nullable
  private Boolean hideLineNumbers;

  public static final String SERIALIZED_NAME_MATCH_BRACKETS = "match_brackets";
  @SerializedName(SERIALIZED_NAME_MATCH_BRACKETS)
  @javax.annotation.Nullable
  private Boolean matchBrackets;

  public static final String SERIALIZED_NAME_LINE_WRAPPING = "line_wrapping";
  @SerializedName(SERIALIZED_NAME_LINE_WRAPPING)
  @javax.annotation.Nullable
  private Boolean lineWrapping;

  public static final String SERIALIZED_NAME_INDENT_WITH_TABS = "indent_with_tabs";
  @SerializedName(SERIALIZED_NAME_INDENT_WITH_TABS)
  @javax.annotation.Nullable
  private Boolean indentWithTabs;

  public static final String SERIALIZED_NAME_AUTO_CLOSE_BRACKETS = "auto_close_brackets";
  @SerializedName(SERIALIZED_NAME_AUTO_CLOSE_BRACKETS)
  @javax.annotation.Nullable
  private Boolean autoCloseBrackets;

  public static final String SERIALIZED_NAME_SHOW_BASE = "show_base";
  @SerializedName(SERIALIZED_NAME_SHOW_BASE)
  @javax.annotation.Nullable
  private Boolean showBase;

  public EditPreferencesInfo() {
  }

  public EditPreferencesInfo tabSize(@javax.annotation.Nullable Integer tabSize) {
    this.tabSize = tabSize;
    return this;
  }

  /**
   * Number of spaces that should be used to display one tab.
   * @return tabSize
   */
  @javax.annotation.Nullable
  public Integer getTabSize() {
    return tabSize;
  }

  public void setTabSize(@javax.annotation.Nullable Integer tabSize) {
    this.tabSize = tabSize;
  }


  public EditPreferencesInfo lineLength(@javax.annotation.Nullable Integer lineLength) {
    this.lineLength = lineLength;
    return this;
  }

  /**
   * Number of characters that should be displayed per line.
   * @return lineLength
   */
  @javax.annotation.Nullable
  public Integer getLineLength() {
    return lineLength;
  }

  public void setLineLength(@javax.annotation.Nullable Integer lineLength) {
    this.lineLength = lineLength;
  }


  public EditPreferencesInfo indentUnit(@javax.annotation.Nullable Integer indentUnit) {
    this.indentUnit = indentUnit;
    return this;
  }

  /**
   * Number of spaces that should be used for auto-indent.
   * @return indentUnit
   */
  @javax.annotation.Nullable
  public Integer getIndentUnit() {
    return indentUnit;
  }

  public void setIndentUnit(@javax.annotation.Nullable Integer indentUnit) {
    this.indentUnit = indentUnit;
  }


  public EditPreferencesInfo cursorBlinkRate(@javax.annotation.Nullable Integer cursorBlinkRate) {
    this.cursorBlinkRate = cursorBlinkRate;
    return this;
  }

  /**
   * Half-period in milliseconds used for cursor blinking. Setting it to 0 disables cursor blinking.
   * @return cursorBlinkRate
   */
  @javax.annotation.Nullable
  public Integer getCursorBlinkRate() {
    return cursorBlinkRate;
  }

  public void setCursorBlinkRate(@javax.annotation.Nullable Integer cursorBlinkRate) {
    this.cursorBlinkRate = cursorBlinkRate;
  }


  public EditPreferencesInfo hideTopMenu(@javax.annotation.Nullable Boolean hideTopMenu) {
    this.hideTopMenu = hideTopMenu;
    return this;
  }

  /**
   * If true the top menu header and site header is hidden.
   * @return hideTopMenu
   */
  @javax.annotation.Nullable
  public Boolean getHideTopMenu() {
    return hideTopMenu;
  }

  public void setHideTopMenu(@javax.annotation.Nullable Boolean hideTopMenu) {
    this.hideTopMenu = hideTopMenu;
  }


  public EditPreferencesInfo showTabs(@javax.annotation.Nullable Boolean showTabs) {
    this.showTabs = showTabs;
    return this;
  }

  /**
   * Whether tabs should be shown.
   * @return showTabs
   */
  @javax.annotation.Nullable
  public Boolean getShowTabs() {
    return showTabs;
  }

  public void setShowTabs(@javax.annotation.Nullable Boolean showTabs) {
    this.showTabs = showTabs;
  }


  public EditPreferencesInfo showWhitespaceErrors(@javax.annotation.Nullable Boolean showWhitespaceErrors) {
    this.showWhitespaceErrors = showWhitespaceErrors;
    return this;
  }

  /**
   * Whether whitespace errors should be shown.
   * @return showWhitespaceErrors
   */
  @javax.annotation.Nullable
  public Boolean getShowWhitespaceErrors() {
    return showWhitespaceErrors;
  }

  public void setShowWhitespaceErrors(@javax.annotation.Nullable Boolean showWhitespaceErrors) {
    this.showWhitespaceErrors = showWhitespaceErrors;
  }


  public EditPreferencesInfo syntaxHighlighting(@javax.annotation.Nullable Boolean syntaxHighlighting) {
    this.syntaxHighlighting = syntaxHighlighting;
    return this;
  }

  /**
   * Whether syntax highlighting should be enabled.
   * @return syntaxHighlighting
   */
  @javax.annotation.Nullable
  public Boolean getSyntaxHighlighting() {
    return syntaxHighlighting;
  }

  public void setSyntaxHighlighting(@javax.annotation.Nullable Boolean syntaxHighlighting) {
    this.syntaxHighlighting = syntaxHighlighting;
  }


  public EditPreferencesInfo hideLineNumbers(@javax.annotation.Nullable Boolean hideLineNumbers) {
    this.hideLineNumbers = hideLineNumbers;
    return this;
  }

  /**
   * Whether line numbers should be hidden.
   * @return hideLineNumbers
   */
  @javax.annotation.Nullable
  public Boolean getHideLineNumbers() {
    return hideLineNumbers;
  }

  public void setHideLineNumbers(@javax.annotation.Nullable Boolean hideLineNumbers) {
    this.hideLineNumbers = hideLineNumbers;
  }


  public EditPreferencesInfo matchBrackets(@javax.annotation.Nullable Boolean matchBrackets) {
    this.matchBrackets = matchBrackets;
    return this;
  }

  /**
   * Whether matching brackets should be highlighted.
   * @return matchBrackets
   */
  @javax.annotation.Nullable
  public Boolean getMatchBrackets() {
    return matchBrackets;
  }

  public void setMatchBrackets(@javax.annotation.Nullable Boolean matchBrackets) {
    this.matchBrackets = matchBrackets;
  }


  public EditPreferencesInfo lineWrapping(@javax.annotation.Nullable Boolean lineWrapping) {
    this.lineWrapping = lineWrapping;
    return this;
  }

  /**
   * Whether to enable line wrapping or not.
   * @return lineWrapping
   */
  @javax.annotation.Nullable
  public Boolean getLineWrapping() {
    return lineWrapping;
  }

  public void setLineWrapping(@javax.annotation.Nullable Boolean lineWrapping) {
    this.lineWrapping = lineWrapping;
  }


  public EditPreferencesInfo indentWithTabs(@javax.annotation.Nullable Boolean indentWithTabs) {
    this.indentWithTabs = indentWithTabs;
    return this;
  }

  /**
   * Whether to indent with tabs or not.
   * @return indentWithTabs
   */
  @javax.annotation.Nullable
  public Boolean getIndentWithTabs() {
    return indentWithTabs;
  }

  public void setIndentWithTabs(@javax.annotation.Nullable Boolean indentWithTabs) {
    this.indentWithTabs = indentWithTabs;
  }


  public EditPreferencesInfo autoCloseBrackets(@javax.annotation.Nullable Boolean autoCloseBrackets) {
    this.autoCloseBrackets = autoCloseBrackets;
    return this;
  }

  /**
   * Whether brackets and quotes should be auto-closed during typing.
   * @return autoCloseBrackets
   */
  @javax.annotation.Nullable
  public Boolean getAutoCloseBrackets() {
    return autoCloseBrackets;
  }

  public void setAutoCloseBrackets(@javax.annotation.Nullable Boolean autoCloseBrackets) {
    this.autoCloseBrackets = autoCloseBrackets;
  }


  public EditPreferencesInfo showBase(@javax.annotation.Nullable Boolean showBase) {
    this.showBase = showBase;
    return this;
  }

  /**
   * Whether to show the inline edit base version or not.
   * @return showBase
   */
  @javax.annotation.Nullable
  public Boolean getShowBase() {
    return showBase;
  }

  public void setShowBase(@javax.annotation.Nullable Boolean showBase) {
    this.showBase = showBase;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditPreferencesInfo editPreferencesInfo = (EditPreferencesInfo) o;
    return Objects.equals(this.tabSize, editPreferencesInfo.tabSize) &&
        Objects.equals(this.lineLength, editPreferencesInfo.lineLength) &&
        Objects.equals(this.indentUnit, editPreferencesInfo.indentUnit) &&
        Objects.equals(this.cursorBlinkRate, editPreferencesInfo.cursorBlinkRate) &&
        Objects.equals(this.hideTopMenu, editPreferencesInfo.hideTopMenu) &&
        Objects.equals(this.showTabs, editPreferencesInfo.showTabs) &&
        Objects.equals(this.showWhitespaceErrors, editPreferencesInfo.showWhitespaceErrors) &&
        Objects.equals(this.syntaxHighlighting, editPreferencesInfo.syntaxHighlighting) &&
        Objects.equals(this.hideLineNumbers, editPreferencesInfo.hideLineNumbers) &&
        Objects.equals(this.matchBrackets, editPreferencesInfo.matchBrackets) &&
        Objects.equals(this.lineWrapping, editPreferencesInfo.lineWrapping) &&
        Objects.equals(this.indentWithTabs, editPreferencesInfo.indentWithTabs) &&
        Objects.equals(this.autoCloseBrackets, editPreferencesInfo.autoCloseBrackets) &&
        Objects.equals(this.showBase, editPreferencesInfo.showBase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tabSize, lineLength, indentUnit, cursorBlinkRate, hideTopMenu, showTabs, showWhitespaceErrors, syntaxHighlighting, hideLineNumbers, matchBrackets, lineWrapping, indentWithTabs, autoCloseBrackets, showBase);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditPreferencesInfo {\n");
    sb.append("    tabSize: ").append(toIndentedString(tabSize)).append("\n");
    sb.append("    lineLength: ").append(toIndentedString(lineLength)).append("\n");
    sb.append("    indentUnit: ").append(toIndentedString(indentUnit)).append("\n");
    sb.append("    cursorBlinkRate: ").append(toIndentedString(cursorBlinkRate)).append("\n");
    sb.append("    hideTopMenu: ").append(toIndentedString(hideTopMenu)).append("\n");
    sb.append("    showTabs: ").append(toIndentedString(showTabs)).append("\n");
    sb.append("    showWhitespaceErrors: ").append(toIndentedString(showWhitespaceErrors)).append("\n");
    sb.append("    syntaxHighlighting: ").append(toIndentedString(syntaxHighlighting)).append("\n");
    sb.append("    hideLineNumbers: ").append(toIndentedString(hideLineNumbers)).append("\n");
    sb.append("    matchBrackets: ").append(toIndentedString(matchBrackets)).append("\n");
    sb.append("    lineWrapping: ").append(toIndentedString(lineWrapping)).append("\n");
    sb.append("    indentWithTabs: ").append(toIndentedString(indentWithTabs)).append("\n");
    sb.append("    autoCloseBrackets: ").append(toIndentedString(autoCloseBrackets)).append("\n");
    sb.append("    showBase: ").append(toIndentedString(showBase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("tab_size", "line_length", "indent_unit", "cursor_blink_rate", "hide_top_menu", "show_tabs", "show_whitespace_errors", "syntax_highlighting", "hide_line_numbers", "match_brackets", "line_wrapping", "indent_with_tabs", "auto_close_brackets", "show_base"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EditPreferencesInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EditPreferencesInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EditPreferencesInfo is not found in the empty JSON string", EditPreferencesInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EditPreferencesInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EditPreferencesInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EditPreferencesInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EditPreferencesInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EditPreferencesInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EditPreferencesInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<EditPreferencesInfo>() {
           @Override
           public void write(JsonWriter out, EditPreferencesInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EditPreferencesInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EditPreferencesInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EditPreferencesInfo
   * @throws IOException if the JSON string is invalid with respect to EditPreferencesInfo
   */
  public static EditPreferencesInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EditPreferencesInfo.class);
  }

  /**
   * Convert an instance of EditPreferencesInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

