/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gerrit.client.model.AccountInfo;
import com.google.gerrit.client.model.ApprovalInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * LabelInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class LabelInfo {
  public static final String SERIALIZED_NAME_APPROVED = "approved";
  @SerializedName(SERIALIZED_NAME_APPROVED)
  @javax.annotation.Nullable
  private AccountInfo approved;

  public static final String SERIALIZED_NAME_REJECTED = "rejected";
  @SerializedName(SERIALIZED_NAME_REJECTED)
  @javax.annotation.Nullable
  private AccountInfo rejected;

  public static final String SERIALIZED_NAME_RECOMMENDED = "recommended";
  @SerializedName(SERIALIZED_NAME_RECOMMENDED)
  @javax.annotation.Nullable
  private AccountInfo recommended;

  public static final String SERIALIZED_NAME_DISLIKED = "disliked";
  @SerializedName(SERIALIZED_NAME_DISLIKED)
  @javax.annotation.Nullable
  private AccountInfo disliked;

  public static final String SERIALIZED_NAME_ALL = "all";
  @SerializedName(SERIALIZED_NAME_ALL)
  @javax.annotation.Nullable
  private List<ApprovalInfo> all = new ArrayList<>();

  public static final String SERIALIZED_NAME_VALUES = "values";
  @SerializedName(SERIALIZED_NAME_VALUES)
  @javax.annotation.Nullable
  private Map<String, String> values = new HashMap<>();

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nullable
  private Integer value;

  public static final String SERIALIZED_NAME_DEFAULT_VALUE = "default_value";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE)
  @javax.annotation.Nullable
  private Integer defaultValue;

  public static final String SERIALIZED_NAME_OPTIONAL = "optional";
  @SerializedName(SERIALIZED_NAME_OPTIONAL)
  @javax.annotation.Nullable
  private Boolean optional;

  public static final String SERIALIZED_NAME_BLOCKING = "blocking";
  @SerializedName(SERIALIZED_NAME_BLOCKING)
  @javax.annotation.Nullable
  private Boolean blocking;

  public LabelInfo() {
  }

  public LabelInfo approved(@javax.annotation.Nullable AccountInfo approved) {
    this.approved = approved;
    return this;
  }

  /**
   * Get approved
   * @return approved
   */
  @javax.annotation.Nullable
  public AccountInfo getApproved() {
    return approved;
  }

  public void setApproved(@javax.annotation.Nullable AccountInfo approved) {
    this.approved = approved;
  }


  public LabelInfo rejected(@javax.annotation.Nullable AccountInfo rejected) {
    this.rejected = rejected;
    return this;
  }

  /**
   * Get rejected
   * @return rejected
   */
  @javax.annotation.Nullable
  public AccountInfo getRejected() {
    return rejected;
  }

  public void setRejected(@javax.annotation.Nullable AccountInfo rejected) {
    this.rejected = rejected;
  }


  public LabelInfo recommended(@javax.annotation.Nullable AccountInfo recommended) {
    this.recommended = recommended;
    return this;
  }

  /**
   * Get recommended
   * @return recommended
   */
  @javax.annotation.Nullable
  public AccountInfo getRecommended() {
    return recommended;
  }

  public void setRecommended(@javax.annotation.Nullable AccountInfo recommended) {
    this.recommended = recommended;
  }


  public LabelInfo disliked(@javax.annotation.Nullable AccountInfo disliked) {
    this.disliked = disliked;
    return this;
  }

  /**
   * Get disliked
   * @return disliked
   */
  @javax.annotation.Nullable
  public AccountInfo getDisliked() {
    return disliked;
  }

  public void setDisliked(@javax.annotation.Nullable AccountInfo disliked) {
    this.disliked = disliked;
  }


  public LabelInfo all(@javax.annotation.Nullable List<ApprovalInfo> all) {
    this.all = all;
    return this;
  }

  public LabelInfo addAllItem(ApprovalInfo allItem) {
    if (this.all == null) {
      this.all = new ArrayList<>();
    }
    this.all.add(allItem);
    return this;
  }

  /**
   * Get all
   * @return all
   */
  @javax.annotation.Nullable
  public List<ApprovalInfo> getAll() {
    return all;
  }

  public void setAll(@javax.annotation.Nullable List<ApprovalInfo> all) {
    this.all = all;
  }


  public LabelInfo values(@javax.annotation.Nullable Map<String, String> values) {
    this.values = values;
    return this;
  }

  public LabelInfo putValuesItem(String key, String valuesItem) {
    if (this.values == null) {
      this.values = new HashMap<>();
    }
    this.values.put(key, valuesItem);
    return this;
  }

  /**
   * Get values
   * @return values
   */
  @javax.annotation.Nullable
  public Map<String, String> getValues() {
    return values;
  }

  public void setValues(@javax.annotation.Nullable Map<String, String> values) {
    this.values = values;
  }


  public LabelInfo description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public LabelInfo value(@javax.annotation.Nullable Integer value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nullable
  public Integer getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nullable Integer value) {
    this.value = value;
  }


  public LabelInfo defaultValue(@javax.annotation.Nullable Integer defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

  /**
   * Get defaultValue
   * @return defaultValue
   */
  @javax.annotation.Nullable
  public Integer getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(@javax.annotation.Nullable Integer defaultValue) {
    this.defaultValue = defaultValue;
  }


  public LabelInfo optional(@javax.annotation.Nullable Boolean optional) {
    this.optional = optional;
    return this;
  }

  /**
   * Get optional
   * @return optional
   */
  @javax.annotation.Nullable
  public Boolean getOptional() {
    return optional;
  }

  public void setOptional(@javax.annotation.Nullable Boolean optional) {
    this.optional = optional;
  }


  public LabelInfo blocking(@javax.annotation.Nullable Boolean blocking) {
    this.blocking = blocking;
    return this;
  }

  /**
   * Get blocking
   * @return blocking
   */
  @javax.annotation.Nullable
  public Boolean getBlocking() {
    return blocking;
  }

  public void setBlocking(@javax.annotation.Nullable Boolean blocking) {
    this.blocking = blocking;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LabelInfo labelInfo = (LabelInfo) o;
    return Objects.equals(this.approved, labelInfo.approved) &&
        Objects.equals(this.rejected, labelInfo.rejected) &&
        Objects.equals(this.recommended, labelInfo.recommended) &&
        Objects.equals(this.disliked, labelInfo.disliked) &&
        Objects.equals(this.all, labelInfo.all) &&
        Objects.equals(this.values, labelInfo.values) &&
        Objects.equals(this.description, labelInfo.description) &&
        Objects.equals(this.value, labelInfo.value) &&
        Objects.equals(this.defaultValue, labelInfo.defaultValue) &&
        Objects.equals(this.optional, labelInfo.optional) &&
        Objects.equals(this.blocking, labelInfo.blocking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approved, rejected, recommended, disliked, all, values, description, value, defaultValue, optional, blocking);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LabelInfo {\n");
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("    rejected: ").append(toIndentedString(rejected)).append("\n");
    sb.append("    recommended: ").append(toIndentedString(recommended)).append("\n");
    sb.append("    disliked: ").append(toIndentedString(disliked)).append("\n");
    sb.append("    all: ").append(toIndentedString(all)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    optional: ").append(toIndentedString(optional)).append("\n");
    sb.append("    blocking: ").append(toIndentedString(blocking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("approved", "rejected", "recommended", "disliked", "all", "values", "description", "value", "default_value", "optional", "blocking"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to LabelInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LabelInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in LabelInfo is not found in the empty JSON string", LabelInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LabelInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `LabelInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `approved`
      if (jsonObj.get("approved") != null && !jsonObj.get("approved").isJsonNull()) {
        AccountInfo.validateJsonElement(jsonObj.get("approved"));
      }
      // validate the optional field `rejected`
      if (jsonObj.get("rejected") != null && !jsonObj.get("rejected").isJsonNull()) {
        AccountInfo.validateJsonElement(jsonObj.get("rejected"));
      }
      // validate the optional field `recommended`
      if (jsonObj.get("recommended") != null && !jsonObj.get("recommended").isJsonNull()) {
        AccountInfo.validateJsonElement(jsonObj.get("recommended"));
      }
      // validate the optional field `disliked`
      if (jsonObj.get("disliked") != null && !jsonObj.get("disliked").isJsonNull()) {
        AccountInfo.validateJsonElement(jsonObj.get("disliked"));
      }
      if (jsonObj.get("all") != null && !jsonObj.get("all").isJsonNull()) {
        JsonArray jsonArrayall = jsonObj.getAsJsonArray("all");
        if (jsonArrayall != null) {
          // ensure the json data is an array
          if (!jsonObj.get("all").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `all` to be an array in the JSON string but got `%s`", jsonObj.get("all").toString()));
          }

          // validate the optional field `all` (array)
          for (int i = 0; i < jsonArrayall.size(); i++) {
            ApprovalInfo.validateJsonElement(jsonArrayall.get(i));
          };
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LabelInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LabelInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LabelInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LabelInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<LabelInfo>() {
           @Override
           public void write(JsonWriter out, LabelInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LabelInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of LabelInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LabelInfo
   * @throws IOException if the JSON string is invalid with respect to LabelInfo
   */
  public static LabelInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LabelInfo.class);
  }

  /**
   * Convert an instance of LabelInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

