/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * MemSummaryInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MemSummaryInfo {
  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nullable
  private String total;

  public static final String SERIALIZED_NAME_USED = "used";
  @SerializedName(SERIALIZED_NAME_USED)
  @javax.annotation.Nullable
  private String used;

  public static final String SERIALIZED_NAME_FREE = "free";
  @SerializedName(SERIALIZED_NAME_FREE)
  @javax.annotation.Nullable
  private String free;

  public static final String SERIALIZED_NAME_BUFFERS = "buffers";
  @SerializedName(SERIALIZED_NAME_BUFFERS)
  @javax.annotation.Nullable
  private String buffers;

  public static final String SERIALIZED_NAME_MAX = "max";
  @SerializedName(SERIALIZED_NAME_MAX)
  @javax.annotation.Nullable
  private String max;

  public static final String SERIALIZED_NAME_OPEN_FILES = "open_files";
  @SerializedName(SERIALIZED_NAME_OPEN_FILES)
  @javax.annotation.Nullable
  private Integer openFiles;

  public MemSummaryInfo() {
  }

  public MemSummaryInfo total(@javax.annotation.Nullable String total) {
    this.total = total;
    return this;
  }

  /**
   * The total size of the memory. The value is returned with a unit abbreviation (k: kilobytes, m: megabytes, g: gigabytes).
   * @return total
   */
  @javax.annotation.Nullable
  public String getTotal() {
    return total;
  }

  public void setTotal(@javax.annotation.Nullable String total) {
    this.total = total;
  }


  public MemSummaryInfo used(@javax.annotation.Nullable String used) {
    this.used = used;
    return this;
  }

  /**
   * The size of used memory. The value is returned with a unit abbreviation (k: kilobytes, m: megabytes, g: gigabytes).
   * @return used
   */
  @javax.annotation.Nullable
  public String getUsed() {
    return used;
  }

  public void setUsed(@javax.annotation.Nullable String used) {
    this.used = used;
  }


  public MemSummaryInfo free(@javax.annotation.Nullable String free) {
    this.free = free;
    return this;
  }

  /**
   * The size of free memory. The value is returned with a unit abbreviation (k: kilobytes, m: megabytes, g: gigabytes).
   * @return free
   */
  @javax.annotation.Nullable
  public String getFree() {
    return free;
  }

  public void setFree(@javax.annotation.Nullable String free) {
    this.free = free;
  }


  public MemSummaryInfo buffers(@javax.annotation.Nullable String buffers) {
    this.buffers = buffers;
    return this;
  }

  /**
   * The size of memory used for JGit buffers. The value is returned with a unit abbreviation (k: kilobytes, m: megabytes, g: gigabytes).
   * @return buffers
   */
  @javax.annotation.Nullable
  public String getBuffers() {
    return buffers;
  }

  public void setBuffers(@javax.annotation.Nullable String buffers) {
    this.buffers = buffers;
  }


  public MemSummaryInfo max(@javax.annotation.Nullable String max) {
    this.max = max;
    return this;
  }

  /**
   * The maximal memory size. The value is returned with a unit abbreviation (k: kilobytes, m: megabytes, g: gigabytes).
   * @return max
   */
  @javax.annotation.Nullable
  public String getMax() {
    return max;
  }

  public void setMax(@javax.annotation.Nullable String max) {
    this.max = max;
  }


  public MemSummaryInfo openFiles(@javax.annotation.Nullable Integer openFiles) {
    this.openFiles = openFiles;
    return this;
  }

  /**
   * The number of open files.
   * @return openFiles
   */
  @javax.annotation.Nullable
  public Integer getOpenFiles() {
    return openFiles;
  }

  public void setOpenFiles(@javax.annotation.Nullable Integer openFiles) {
    this.openFiles = openFiles;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemSummaryInfo memSummaryInfo = (MemSummaryInfo) o;
    return Objects.equals(this.total, memSummaryInfo.total) &&
        Objects.equals(this.used, memSummaryInfo.used) &&
        Objects.equals(this.free, memSummaryInfo.free) &&
        Objects.equals(this.buffers, memSummaryInfo.buffers) &&
        Objects.equals(this.max, memSummaryInfo.max) &&
        Objects.equals(this.openFiles, memSummaryInfo.openFiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, used, free, buffers, max, openFiles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemSummaryInfo {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    free: ").append(toIndentedString(free)).append("\n");
    sb.append("    buffers: ").append(toIndentedString(buffers)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    openFiles: ").append(toIndentedString(openFiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("total", "used", "free", "buffers", "max", "open_files"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MemSummaryInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MemSummaryInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MemSummaryInfo is not found in the empty JSON string", MemSummaryInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MemSummaryInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MemSummaryInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("total") != null && !jsonObj.get("total").isJsonNull()) && !jsonObj.get("total").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `total` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total").toString()));
      }
      if ((jsonObj.get("used") != null && !jsonObj.get("used").isJsonNull()) && !jsonObj.get("used").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `used` to be a primitive type in the JSON string but got `%s`", jsonObj.get("used").toString()));
      }
      if ((jsonObj.get("free") != null && !jsonObj.get("free").isJsonNull()) && !jsonObj.get("free").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `free` to be a primitive type in the JSON string but got `%s`", jsonObj.get("free").toString()));
      }
      if ((jsonObj.get("buffers") != null && !jsonObj.get("buffers").isJsonNull()) && !jsonObj.get("buffers").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `buffers` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buffers").toString()));
      }
      if ((jsonObj.get("max") != null && !jsonObj.get("max").isJsonNull()) && !jsonObj.get("max").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `max` to be a primitive type in the JSON string but got `%s`", jsonObj.get("max").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MemSummaryInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MemSummaryInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MemSummaryInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MemSummaryInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<MemSummaryInfo>() {
           @Override
           public void write(JsonWriter out, MemSummaryInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MemSummaryInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MemSummaryInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MemSummaryInfo
   * @throws IOException if the JSON string is invalid with respect to MemSummaryInfo
   */
  public static MemSummaryInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MemSummaryInfo.class);
  }

  /**
   * Convert an instance of MemSummaryInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

