/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gerrit.client.model.AccessSectionInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * ProjectAccessInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ProjectAccessInput {
  public static final String SERIALIZED_NAME_REMOVE = "remove";
  @SerializedName(SERIALIZED_NAME_REMOVE)
  @javax.annotation.Nullable
  private Map<String, AccessSectionInfo> remove = new HashMap<>();

  public static final String SERIALIZED_NAME_ADD = "add";
  @SerializedName(SERIALIZED_NAME_ADD)
  @javax.annotation.Nullable
  private Map<String, AccessSectionInfo> add = new HashMap<>();

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  @javax.annotation.Nullable
  private String parent;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public ProjectAccessInput() {
  }

  public ProjectAccessInput remove(@javax.annotation.Nullable Map<String, AccessSectionInfo> remove) {
    this.remove = remove;
    return this;
  }

  public ProjectAccessInput putRemoveItem(String key, AccessSectionInfo removeItem) {
    if (this.remove == null) {
      this.remove = new HashMap<>();
    }
    this.remove.put(key, removeItem);
    return this;
  }

  /**
   * A map of deductions to be applied to the project access, mapping refs to AccessSectionInfo entities.
   * @return remove
   */
  @javax.annotation.Nullable
  public Map<String, AccessSectionInfo> getRemove() {
    return remove;
  }

  public void setRemove(@javax.annotation.Nullable Map<String, AccessSectionInfo> remove) {
    this.remove = remove;
  }


  public ProjectAccessInput add(@javax.annotation.Nullable Map<String, AccessSectionInfo> add) {
    this.add = add;
    return this;
  }

  public ProjectAccessInput putAddItem(String key, AccessSectionInfo addItem) {
    if (this.add == null) {
      this.add = new HashMap<>();
    }
    this.add.put(key, addItem);
    return this;
  }

  /**
   * A map of additions to be applied to the project access, mapping refs to AccessSectionInfo entities.
   * @return add
   */
  @javax.annotation.Nullable
  public Map<String, AccessSectionInfo> getAdd() {
    return add;
  }

  public void setAdd(@javax.annotation.Nullable Map<String, AccessSectionInfo> add) {
    this.add = add;
  }


  public ProjectAccessInput parent(@javax.annotation.Nullable String parent) {
    this.parent = parent;
    return this;
  }

  /**
   * A new parent for the project to inherit from. Changing the parent project requires administrative privileges.
   * @return parent
   */
  @javax.annotation.Nullable
  public String getParent() {
    return parent;
  }

  public void setParent(@javax.annotation.Nullable String parent) {
    this.parent = parent;
  }


  public ProjectAccessInput message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * A commit message for this change.
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectAccessInput projectAccessInput = (ProjectAccessInput) o;
    return Objects.equals(this.remove, projectAccessInput.remove) &&
        Objects.equals(this.add, projectAccessInput.add) &&
        Objects.equals(this.parent, projectAccessInput.parent) &&
        Objects.equals(this.message, projectAccessInput.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(remove, add, parent, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectAccessInput {\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("remove", "add", "parent", "message"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProjectAccessInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProjectAccessInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ProjectAccessInput is not found in the empty JSON string", ProjectAccessInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProjectAccessInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ProjectAccessInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("parent") != null && !jsonObj.get("parent").isJsonNull()) && !jsonObj.get("parent").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parent` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProjectAccessInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProjectAccessInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProjectAccessInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProjectAccessInput.class));

       return (TypeAdapter<T>) new TypeAdapter<ProjectAccessInput>() {
           @Override
           public void write(JsonWriter out, ProjectAccessInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProjectAccessInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProjectAccessInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProjectAccessInput
   * @throws IOException if the JSON string is invalid with respect to ProjectAccessInput
   */
  public static ProjectAccessInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProjectAccessInput.class);
  }

  /**
   * Convert an instance of ProjectAccessInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

