/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * RebaseInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class RebaseInput {
  public static final String SERIALIZED_NAME_BASE = "base";
  @SerializedName(SERIALIZED_NAME_BASE)
  @javax.annotation.Nullable
  private String base;

  public static final String SERIALIZED_NAME_STRATEGY = "strategy";
  @SerializedName(SERIALIZED_NAME_STRATEGY)
  @javax.annotation.Nullable
  private String strategy;

  public static final String SERIALIZED_NAME_ALLOW_CONFLICTS = "allow_conflicts";
  @SerializedName(SERIALIZED_NAME_ALLOW_CONFLICTS)
  @javax.annotation.Nullable
  private Boolean allowConflicts;

  public static final String SERIALIZED_NAME_ON_BEHALF_OF_UPLOADER = "on_behalf_of_uploader";
  @SerializedName(SERIALIZED_NAME_ON_BEHALF_OF_UPLOADER)
  @javax.annotation.Nullable
  private Boolean onBehalfOfUploader;

  public static final String SERIALIZED_NAME_VALIDATION_OPTIONS = "validation_options";
  @SerializedName(SERIALIZED_NAME_VALIDATION_OPTIONS)
  @javax.annotation.Nullable
  private Map<String, String> validationOptions = new HashMap<>();

  public static final String SERIALIZED_NAME_COMMITTER_EMAIL = "committer_email";
  @SerializedName(SERIALIZED_NAME_COMMITTER_EMAIL)
  @javax.annotation.Nullable
  private String committerEmail;

  public RebaseInput() {
  }

  public RebaseInput base(@javax.annotation.Nullable String base) {
    this.base = base;
    return this;
  }

  /**
   * The new parent revision. This can be a ref or a SHA-1 to a concrete patchset. + Alternatively, a change number can be specified, in which case the current patch set is inferred.
   * @return base
   */
  @javax.annotation.Nullable
  public String getBase() {
    return base;
  }

  public void setBase(@javax.annotation.Nullable String base) {
    this.base = base;
  }


  public RebaseInput strategy(@javax.annotation.Nullable String strategy) {
    this.strategy = strategy;
    return this;
  }

  /**
   * The strategy of the merge, can be recursive, resolve, simple-two-way-in-core, ours or theirs, default will use project settings.
   * @return strategy
   */
  @javax.annotation.Nullable
  public String getStrategy() {
    return strategy;
  }

  public void setStrategy(@javax.annotation.Nullable String strategy) {
    this.strategy = strategy;
  }


  public RebaseInput allowConflicts(@javax.annotation.Nullable Boolean allowConflicts) {
    this.allowConflicts = allowConflicts;
    return this;
  }

  /**
   * If true, the rebase also succeeds if there are conflicts. + If there are conflicts the file contents of the rebased patch set contain git conflict markers to indicate the conflicts.
   * @return allowConflicts
   */
  @javax.annotation.Nullable
  public Boolean getAllowConflicts() {
    return allowConflicts;
  }

  public void setAllowConflicts(@javax.annotation.Nullable Boolean allowConflicts) {
    this.allowConflicts = allowConflicts;
  }


  public RebaseInput onBehalfOfUploader(@javax.annotation.Nullable Boolean onBehalfOfUploader) {
    this.onBehalfOfUploader = onBehalfOfUploader;
    return this;
  }

  /**
   * If true, the rebase is done on behalf of the uploader. + This means the uploader of the current patch set will also be the uploader of the rebased patch set. The calling user will be recorded as the real user. + Rebasing on behalf of the uploader is only supported for trivial rebases.
   * @return onBehalfOfUploader
   */
  @javax.annotation.Nullable
  public Boolean getOnBehalfOfUploader() {
    return onBehalfOfUploader;
  }

  public void setOnBehalfOfUploader(@javax.annotation.Nullable Boolean onBehalfOfUploader) {
    this.onBehalfOfUploader = onBehalfOfUploader;
  }


  public RebaseInput validationOptions(@javax.annotation.Nullable Map<String, String> validationOptions) {
    this.validationOptions = validationOptions;
    return this;
  }

  public RebaseInput putValidationOptionsItem(String key, String validationOptionsItem) {
    if (this.validationOptions == null) {
      this.validationOptions = new HashMap<>();
    }
    this.validationOptions.put(key, validationOptionsItem);
    return this;
  }

  /**
   * Map with key-value pairs that are forwarded as options to the commit validation listeners (e.g. can be used to skip certain validations). Which validation options are supported depends on the installed commit validation listeners.
   * @return validationOptions
   */
  @javax.annotation.Nullable
  public Map<String, String> getValidationOptions() {
    return validationOptions;
  }

  public void setValidationOptions(@javax.annotation.Nullable Map<String, String> validationOptions) {
    this.validationOptions = validationOptions;
  }


  public RebaseInput committerEmail(@javax.annotation.Nullable String committerEmail) {
    this.committerEmail = committerEmail;
    return this;
  }

  /**
   * Rebase is committed using this email address. Only the registered emails of the calling user or uploader (when on_behalf_of_uploader is true) are considered valid. This option is not supported when rebasing a chain.
   * @return committerEmail
   */
  @javax.annotation.Nullable
  public String getCommitterEmail() {
    return committerEmail;
  }

  public void setCommitterEmail(@javax.annotation.Nullable String committerEmail) {
    this.committerEmail = committerEmail;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RebaseInput rebaseInput = (RebaseInput) o;
    return Objects.equals(this.base, rebaseInput.base) &&
        Objects.equals(this.strategy, rebaseInput.strategy) &&
        Objects.equals(this.allowConflicts, rebaseInput.allowConflicts) &&
        Objects.equals(this.onBehalfOfUploader, rebaseInput.onBehalfOfUploader) &&
        Objects.equals(this.validationOptions, rebaseInput.validationOptions) &&
        Objects.equals(this.committerEmail, rebaseInput.committerEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(base, strategy, allowConflicts, onBehalfOfUploader, validationOptions, committerEmail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RebaseInput {\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("    allowConflicts: ").append(toIndentedString(allowConflicts)).append("\n");
    sb.append("    onBehalfOfUploader: ").append(toIndentedString(onBehalfOfUploader)).append("\n");
    sb.append("    validationOptions: ").append(toIndentedString(validationOptions)).append("\n");
    sb.append("    committerEmail: ").append(toIndentedString(committerEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("base", "strategy", "allow_conflicts", "on_behalf_of_uploader", "validation_options", "committer_email"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RebaseInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RebaseInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RebaseInput is not found in the empty JSON string", RebaseInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RebaseInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RebaseInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("base") != null && !jsonObj.get("base").isJsonNull()) && !jsonObj.get("base").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `base` to be a primitive type in the JSON string but got `%s`", jsonObj.get("base").toString()));
      }
      if ((jsonObj.get("strategy") != null && !jsonObj.get("strategy").isJsonNull()) && !jsonObj.get("strategy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `strategy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("strategy").toString()));
      }
      if ((jsonObj.get("committer_email") != null && !jsonObj.get("committer_email").isJsonNull()) && !jsonObj.get("committer_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `committer_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("committer_email").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RebaseInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RebaseInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RebaseInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RebaseInput.class));

       return (TypeAdapter<T>) new TypeAdapter<RebaseInput>() {
           @Override
           public void write(JsonWriter out, RebaseInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RebaseInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RebaseInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RebaseInput
   * @throws IOException if the JSON string is invalid with respect to RebaseInput
   */
  public static RebaseInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RebaseInput.class);
  }

  /**
   * Convert an instance of RebaseInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

