/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gerrit.client.model.NotifyHandling;
import com.google.gerrit.client.model.NotifyInfo;
import com.google.gerrit.client.model.ReviewerState;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * ReviewerInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ReviewerInput {
  public static final String SERIALIZED_NAME_REVIEWER = "reviewer";
  @SerializedName(SERIALIZED_NAME_REVIEWER)
  @javax.annotation.Nullable
  private String reviewer;

  public static final String SERIALIZED_NAME_CONFIRMED = "confirmed";
  @SerializedName(SERIALIZED_NAME_CONFIRMED)
  @javax.annotation.Nullable
  private Boolean confirmed;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nullable
  private ReviewerState state;

  public static final String SERIALIZED_NAME_NOTIFY = "notify";
  @SerializedName(SERIALIZED_NAME_NOTIFY)
  @javax.annotation.Nullable
  private NotifyHandling notify;

  public static final String SERIALIZED_NAME_NOTIFY_DETAILS = "notify_details";
  @SerializedName(SERIALIZED_NAME_NOTIFY_DETAILS)
  @javax.annotation.Nullable
  private Map<String, NotifyInfo> notifyDetails = new HashMap<>();

  public static final String SERIALIZED_NAME_ON_BEHALF_OF = "on_behalf_of";
  @SerializedName(SERIALIZED_NAME_ON_BEHALF_OF)
  @javax.annotation.Nullable
  private String onBehalfOf;

  public ReviewerInput() {
  }

  public ReviewerInput reviewer(@javax.annotation.Nullable String reviewer) {
    this.reviewer = reviewer;
    return this;
  }

  /**
   * Get reviewer
   * @return reviewer
   */
  @javax.annotation.Nullable
  public String getReviewer() {
    return reviewer;
  }

  public void setReviewer(@javax.annotation.Nullable String reviewer) {
    this.reviewer = reviewer;
  }


  public ReviewerInput confirmed(@javax.annotation.Nullable Boolean confirmed) {
    this.confirmed = confirmed;
    return this;
  }

  /**
   * Get confirmed
   * @return confirmed
   */
  @javax.annotation.Nullable
  public Boolean getConfirmed() {
    return confirmed;
  }

  public void setConfirmed(@javax.annotation.Nullable Boolean confirmed) {
    this.confirmed = confirmed;
  }


  public ReviewerInput state(@javax.annotation.Nullable ReviewerState state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nullable
  public ReviewerState getState() {
    return state;
  }

  public void setState(@javax.annotation.Nullable ReviewerState state) {
    this.state = state;
  }


  public ReviewerInput notify(@javax.annotation.Nullable NotifyHandling notify) {
    this.notify = notify;
    return this;
  }

  /**
   * Get notify
   * @return notify
   */
  @javax.annotation.Nullable
  public NotifyHandling getNotify() {
    return notify;
  }

  public void setNotify(@javax.annotation.Nullable NotifyHandling notify) {
    this.notify = notify;
  }


  public ReviewerInput notifyDetails(@javax.annotation.Nullable Map<String, NotifyInfo> notifyDetails) {
    this.notifyDetails = notifyDetails;
    return this;
  }

  public ReviewerInput putNotifyDetailsItem(String key, NotifyInfo notifyDetailsItem) {
    if (this.notifyDetails == null) {
      this.notifyDetails = new HashMap<>();
    }
    this.notifyDetails.put(key, notifyDetailsItem);
    return this;
  }

  /**
   * Get notifyDetails
   * @return notifyDetails
   */
  @javax.annotation.Nullable
  public Map<String, NotifyInfo> getNotifyDetails() {
    return notifyDetails;
  }

  public void setNotifyDetails(@javax.annotation.Nullable Map<String, NotifyInfo> notifyDetails) {
    this.notifyDetails = notifyDetails;
  }


  public ReviewerInput onBehalfOf(@javax.annotation.Nullable String onBehalfOf) {
    this.onBehalfOf = onBehalfOf;
    return this;
  }

  /**
   * Get onBehalfOf
   * @return onBehalfOf
   */
  @javax.annotation.Nullable
  public String getOnBehalfOf() {
    return onBehalfOf;
  }

  public void setOnBehalfOf(@javax.annotation.Nullable String onBehalfOf) {
    this.onBehalfOf = onBehalfOf;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReviewerInput reviewerInput = (ReviewerInput) o;
    return Objects.equals(this.reviewer, reviewerInput.reviewer) &&
        Objects.equals(this.confirmed, reviewerInput.confirmed) &&
        Objects.equals(this.state, reviewerInput.state) &&
        Objects.equals(this.notify, reviewerInput.notify) &&
        Objects.equals(this.notifyDetails, reviewerInput.notifyDetails) &&
        Objects.equals(this.onBehalfOf, reviewerInput.onBehalfOf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reviewer, confirmed, state, notify, notifyDetails, onBehalfOf);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReviewerInput {\n");
    sb.append("    reviewer: ").append(toIndentedString(reviewer)).append("\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    notify: ").append(toIndentedString(notify)).append("\n");
    sb.append("    notifyDetails: ").append(toIndentedString(notifyDetails)).append("\n");
    sb.append("    onBehalfOf: ").append(toIndentedString(onBehalfOf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("reviewer", "confirmed", "state", "notify", "notify_details", "on_behalf_of"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReviewerInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReviewerInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ReviewerInput is not found in the empty JSON string", ReviewerInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReviewerInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ReviewerInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("reviewer") != null && !jsonObj.get("reviewer").isJsonNull()) && !jsonObj.get("reviewer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `reviewer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reviewer").toString()));
      }
      // validate the optional field `state`
      if (jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) {
        ReviewerState.validateJsonElement(jsonObj.get("state"));
      }
      // validate the optional field `notify`
      if (jsonObj.get("notify") != null && !jsonObj.get("notify").isJsonNull()) {
        NotifyHandling.validateJsonElement(jsonObj.get("notify"));
      }
      if ((jsonObj.get("on_behalf_of") != null && !jsonObj.get("on_behalf_of").isJsonNull()) && !jsonObj.get("on_behalf_of").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `on_behalf_of` to be a primitive type in the JSON string but got `%s`", jsonObj.get("on_behalf_of").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReviewerInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReviewerInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReviewerInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReviewerInput.class));

       return (TypeAdapter<T>) new TypeAdapter<ReviewerInput>() {
           @Override
           public void write(JsonWriter out, ReviewerInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReviewerInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReviewerInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReviewerInput
   * @throws IOException if the JSON string is invalid with respect to ReviewerInput
   */
  public static ReviewerInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReviewerInput.class);
  }

  /**
   * Convert an instance of ReviewerInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

