/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gerrit.client.model.AccountInfo;
import com.google.gerrit.client.model.ReviewerInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * ReviewerResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ReviewerResult {
  public static final String SERIALIZED_NAME_INPUT = "input";
  @SerializedName(SERIALIZED_NAME_INPUT)
  @javax.annotation.Nullable
  private String input;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @javax.annotation.Nullable
  private String error;

  public static final String SERIALIZED_NAME_CONFIRM = "confirm";
  @SerializedName(SERIALIZED_NAME_CONFIRM)
  @javax.annotation.Nullable
  private Boolean confirm;

  public static final String SERIALIZED_NAME_REVIEWERS = "reviewers";
  @SerializedName(SERIALIZED_NAME_REVIEWERS)
  @javax.annotation.Nullable
  private List<ReviewerInfo> reviewers = new ArrayList<>();

  public static final String SERIALIZED_NAME_CCS = "ccs";
  @SerializedName(SERIALIZED_NAME_CCS)
  @javax.annotation.Nullable
  private List<AccountInfo> ccs = new ArrayList<>();

  public static final String SERIALIZED_NAME_REMOVED = "removed";
  @SerializedName(SERIALIZED_NAME_REMOVED)
  @javax.annotation.Nullable
  private AccountInfo removed;

  public ReviewerResult() {
  }

  public ReviewerResult input(@javax.annotation.Nullable String input) {
    this.input = input;
    return this;
  }

  /**
   * Value of the reviewer field from ReviewerInput set while adding the reviewer.
   * @return input
   */
  @javax.annotation.Nullable
  public String getInput() {
    return input;
  }

  public void setInput(@javax.annotation.Nullable String input) {
    this.input = input;
  }


  public ReviewerResult error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Error message explaining why the reviewer could not be added. + If a group was specified in the input and an error is returned, it means that none of the members were added as reviewer.
   * @return error
   */
  @javax.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  public ReviewerResult confirm(@javax.annotation.Nullable Boolean confirm) {
    this.confirm = confirm;
    return this;
  }

  /**
   * Whether adding the reviewer requires confirmation.
   * @return confirm
   */
  @javax.annotation.Nullable
  public Boolean getConfirm() {
    return confirm;
  }

  public void setConfirm(@javax.annotation.Nullable Boolean confirm) {
    this.confirm = confirm;
  }


  public ReviewerResult reviewers(@javax.annotation.Nullable List<ReviewerInfo> reviewers) {
    this.reviewers = reviewers;
    return this;
  }

  public ReviewerResult addReviewersItem(ReviewerInfo reviewersItem) {
    if (this.reviewers == null) {
      this.reviewers = new ArrayList<>();
    }
    this.reviewers.add(reviewersItem);
    return this;
  }

  /**
   * The newly added reviewers as a list of ReviewerInfo entities.
   * @return reviewers
   */
  @javax.annotation.Nullable
  public List<ReviewerInfo> getReviewers() {
    return reviewers;
  }

  public void setReviewers(@javax.annotation.Nullable List<ReviewerInfo> reviewers) {
    this.reviewers = reviewers;
  }


  public ReviewerResult ccs(@javax.annotation.Nullable List<AccountInfo> ccs) {
    this.ccs = ccs;
    return this;
  }

  public ReviewerResult addCcsItem(AccountInfo ccsItem) {
    if (this.ccs == null) {
      this.ccs = new ArrayList<>();
    }
    this.ccs.add(ccsItem);
    return this;
  }

  /**
   * The newly CCed accounts as a list of AccountInfo entities. This field will only appear if the requested state for the reviewer was CC.
   * @return ccs
   */
  @javax.annotation.Nullable
  public List<AccountInfo> getCcs() {
    return ccs;
  }

  public void setCcs(@javax.annotation.Nullable List<AccountInfo> ccs) {
    this.ccs = ccs;
  }


  public ReviewerResult removed(@javax.annotation.Nullable AccountInfo removed) {
    this.removed = removed;
    return this;
  }

  /**
   * The newly removed accounts as a list of AccountInfo entities. This field will only appear if the requested state for the reviewer was REMOVED.
   * @return removed
   */
  @javax.annotation.Nullable
  public AccountInfo getRemoved() {
    return removed;
  }

  public void setRemoved(@javax.annotation.Nullable AccountInfo removed) {
    this.removed = removed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReviewerResult reviewerResult = (ReviewerResult) o;
    return Objects.equals(this.input, reviewerResult.input) &&
        Objects.equals(this.error, reviewerResult.error) &&
        Objects.equals(this.confirm, reviewerResult.confirm) &&
        Objects.equals(this.reviewers, reviewerResult.reviewers) &&
        Objects.equals(this.ccs, reviewerResult.ccs) &&
        Objects.equals(this.removed, reviewerResult.removed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, error, confirm, reviewers, ccs, removed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReviewerResult {\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    confirm: ").append(toIndentedString(confirm)).append("\n");
    sb.append("    reviewers: ").append(toIndentedString(reviewers)).append("\n");
    sb.append("    ccs: ").append(toIndentedString(ccs)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("input", "error", "confirm", "reviewers", "ccs", "removed"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReviewerResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReviewerResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ReviewerResult is not found in the empty JSON string", ReviewerResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReviewerResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ReviewerResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("input") != null && !jsonObj.get("input").isJsonNull()) && !jsonObj.get("input").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `input` to be a primitive type in the JSON string but got `%s`", jsonObj.get("input").toString()));
      }
      if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
      if (jsonObj.get("reviewers") != null && !jsonObj.get("reviewers").isJsonNull()) {
        JsonArray jsonArrayreviewers = jsonObj.getAsJsonArray("reviewers");
        if (jsonArrayreviewers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("reviewers").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `reviewers` to be an array in the JSON string but got `%s`", jsonObj.get("reviewers").toString()));
          }

          // validate the optional field `reviewers` (array)
          for (int i = 0; i < jsonArrayreviewers.size(); i++) {
            ReviewerInfo.validateJsonElement(jsonArrayreviewers.get(i));
          };
        }
      }
      if (jsonObj.get("ccs") != null && !jsonObj.get("ccs").isJsonNull()) {
        JsonArray jsonArrayccs = jsonObj.getAsJsonArray("ccs");
        if (jsonArrayccs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ccs").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ccs` to be an array in the JSON string but got `%s`", jsonObj.get("ccs").toString()));
          }

          // validate the optional field `ccs` (array)
          for (int i = 0; i < jsonArrayccs.size(); i++) {
            AccountInfo.validateJsonElement(jsonArrayccs.get(i));
          };
        }
      }
      // validate the optional field `removed`
      if (jsonObj.get("removed") != null && !jsonObj.get("removed").isJsonNull()) {
        AccountInfo.validateJsonElement(jsonObj.get("removed"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReviewerResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReviewerResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReviewerResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReviewerResult.class));

       return (TypeAdapter<T>) new TypeAdapter<ReviewerResult>() {
           @Override
           public void write(JsonWriter out, ReviewerResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReviewerResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReviewerResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReviewerResult
   * @throws IOException if the JSON string is invalid with respect to ReviewerResult
   */
  public static ReviewerResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReviewerResult.class);
  }

  /**
   * Convert an instance of ReviewerResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

