/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gerrit.client.model.ChangeInfo;
import com.google.gerrit.client.model.ReviewerResult;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * ReviewResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ReviewResult {
  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  @javax.annotation.Nullable
  private Map<String, Integer> labels = new HashMap<>();

  public static final String SERIALIZED_NAME_REVIEWERS = "reviewers";
  @SerializedName(SERIALIZED_NAME_REVIEWERS)
  @javax.annotation.Nullable
  private Map<String, ReviewerResult> reviewers = new HashMap<>();

  public static final String SERIALIZED_NAME_READY = "ready";
  @SerializedName(SERIALIZED_NAME_READY)
  @javax.annotation.Nullable
  private Boolean ready;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @javax.annotation.Nullable
  private String error;

  public static final String SERIALIZED_NAME_CHANGE_INFO = "change_info";
  @SerializedName(SERIALIZED_NAME_CHANGE_INFO)
  @javax.annotation.Nullable
  private ChangeInfo changeInfo;

  public ReviewResult() {
  }

  public ReviewResult labels(@javax.annotation.Nullable Map<String, Integer> labels) {
    this.labels = labels;
    return this;
  }

  public ReviewResult putLabelsItem(String key, Integer labelsItem) {
    if (this.labels == null) {
      this.labels = new HashMap<>();
    }
    this.labels.put(key, labelsItem);
    return this;
  }

  /**
   * Map of labels to values after the review was posted. Null if any reviewer additions were rejected.
   * @return labels
   */
  @javax.annotation.Nullable
  public Map<String, Integer> getLabels() {
    return labels;
  }

  public void setLabels(@javax.annotation.Nullable Map<String, Integer> labels) {
    this.labels = labels;
  }


  public ReviewResult reviewers(@javax.annotation.Nullable Map<String, ReviewerResult> reviewers) {
    this.reviewers = reviewers;
    return this;
  }

  public ReviewResult putReviewersItem(String key, ReviewerResult reviewersItem) {
    if (this.reviewers == null) {
      this.reviewers = new HashMap<>();
    }
    this.reviewers.put(key, reviewersItem);
    return this;
  }

  /**
   * Map of account or group identifier to ReviewerResult representing the outcome of adding/removing a reviewer. Absent if no reviewer additions were requested.
   * @return reviewers
   */
  @javax.annotation.Nullable
  public Map<String, ReviewerResult> getReviewers() {
    return reviewers;
  }

  public void setReviewers(@javax.annotation.Nullable Map<String, ReviewerResult> reviewers) {
    this.reviewers = reviewers;
  }


  public ReviewResult ready(@javax.annotation.Nullable Boolean ready) {
    this.ready = ready;
    return this;
  }

  /**
   * If true, the change was moved from WIP to ready for review as a result of this action. Not set if false.
   * @return ready
   */
  @javax.annotation.Nullable
  public Boolean getReady() {
    return ready;
  }

  public void setReady(@javax.annotation.Nullable Boolean ready) {
    this.ready = ready;
  }


  public ReviewResult error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Error message for non-200 responses.
   * @return error
   */
  @javax.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  public ReviewResult changeInfo(@javax.annotation.Nullable ChangeInfo changeInfo) {
    this.changeInfo = changeInfo;
    return this;
  }

  /**
   * Post-update change information.
   * @return changeInfo
   */
  @javax.annotation.Nullable
  public ChangeInfo getChangeInfo() {
    return changeInfo;
  }

  public void setChangeInfo(@javax.annotation.Nullable ChangeInfo changeInfo) {
    this.changeInfo = changeInfo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReviewResult reviewResult = (ReviewResult) o;
    return Objects.equals(this.labels, reviewResult.labels) &&
        Objects.equals(this.reviewers, reviewResult.reviewers) &&
        Objects.equals(this.ready, reviewResult.ready) &&
        Objects.equals(this.error, reviewResult.error) &&
        Objects.equals(this.changeInfo, reviewResult.changeInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labels, reviewers, ready, error, changeInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReviewResult {\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    reviewers: ").append(toIndentedString(reviewers)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    changeInfo: ").append(toIndentedString(changeInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("labels", "reviewers", "ready", "error", "change_info"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReviewResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReviewResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ReviewResult is not found in the empty JSON string", ReviewResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReviewResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ReviewResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
      // validate the optional field `change_info`
      if (jsonObj.get("change_info") != null && !jsonObj.get("change_info").isJsonNull()) {
        ChangeInfo.validateJsonElement(jsonObj.get("change_info"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReviewResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReviewResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReviewResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReviewResult.class));

       return (TypeAdapter<T>) new TypeAdapter<ReviewResult>() {
           @Override
           public void write(JsonWriter out, ReviewResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReviewResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReviewResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReviewResult
   * @throws IOException if the JSON string is invalid with respect to ReviewResult
   */
  public static ReviewResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReviewResult.class);
  }

  /**
   * Convert an instance of ReviewResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

