/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets SubmitRecordInfoStatus
 */
@JsonAdapter(SubmitRecordInfoStatus.Adapter.class)
public enum SubmitRecordInfoStatus {
  
  OK("OK"),
  
  NOT_READY("NOT_READY"),
  
  CLOSED("CLOSED"),
  
  FORCED("FORCED"),
  
  RULE_ERROR("RULE_ERROR");

  private String value;

  SubmitRecordInfoStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SubmitRecordInfoStatus fromValue(String value) {
    for (SubmitRecordInfoStatus b : SubmitRecordInfoStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SubmitRecordInfoStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final SubmitRecordInfoStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SubmitRecordInfoStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SubmitRecordInfoStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    SubmitRecordInfoStatus.fromValue(value);
  }
}

