/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets SubmitRequirementExpressionInfoStatus
 */
@JsonAdapter(SubmitRequirementExpressionInfoStatus.Adapter.class)
public enum SubmitRequirementExpressionInfoStatus {
  
  PASS("PASS"),
  
  FAIL("FAIL"),
  
  ERROR("ERROR"),
  
  NOT_EVALUATED("NOT_EVALUATED"),
  
  TIMEOUT("TIMEOUT");

  private String value;

  SubmitRequirementExpressionInfoStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SubmitRequirementExpressionInfoStatus fromValue(String value) {
    for (SubmitRequirementExpressionInfoStatus b : SubmitRequirementExpressionInfoStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SubmitRequirementExpressionInfoStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final SubmitRequirementExpressionInfoStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SubmitRequirementExpressionInfoStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SubmitRequirementExpressionInfoStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    SubmitRequirementExpressionInfoStatus.fromValue(value);
  }
}

