/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.gerrit.client.JSON;

/**
 * SubmitRequirementInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class SubmitRequirementInfo {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_PROJECT_NAME = "project_name";
  @SerializedName(SERIALIZED_NAME_PROJECT_NAME)
  @javax.annotation.Nullable
  private String projectName;

  public static final String SERIALIZED_NAME_APPLICABILITY_EXPRESSION = "applicability_expression";
  @SerializedName(SERIALIZED_NAME_APPLICABILITY_EXPRESSION)
  @javax.annotation.Nullable
  private String applicabilityExpression;

  public static final String SERIALIZED_NAME_SUBMITTABILITY_EXPRESSION = "submittability_expression";
  @SerializedName(SERIALIZED_NAME_SUBMITTABILITY_EXPRESSION)
  @javax.annotation.Nullable
  private String submittabilityExpression;

  public static final String SERIALIZED_NAME_OVERRIDE_EXPRESSION = "override_expression";
  @SerializedName(SERIALIZED_NAME_OVERRIDE_EXPRESSION)
  @javax.annotation.Nullable
  private String overrideExpression;

  public static final String SERIALIZED_NAME_ALLOW_OVERRIDE_IN_CHILD_PROJECTS = "allow_override_in_child_projects";
  @SerializedName(SERIALIZED_NAME_ALLOW_OVERRIDE_IN_CHILD_PROJECTS)
  @javax.annotation.Nullable
  private Boolean allowOverrideInChildProjects;

  public SubmitRequirementInfo() {
  }

  public SubmitRequirementInfo name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public SubmitRequirementInfo description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public SubmitRequirementInfo projectName(@javax.annotation.Nullable String projectName) {
    this.projectName = projectName;
    return this;
  }

  /**
   * Get projectName
   * @return projectName
   */
  @javax.annotation.Nullable
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(@javax.annotation.Nullable String projectName) {
    this.projectName = projectName;
  }


  public SubmitRequirementInfo applicabilityExpression(@javax.annotation.Nullable String applicabilityExpression) {
    this.applicabilityExpression = applicabilityExpression;
    return this;
  }

  /**
   * Get applicabilityExpression
   * @return applicabilityExpression
   */
  @javax.annotation.Nullable
  public String getApplicabilityExpression() {
    return applicabilityExpression;
  }

  public void setApplicabilityExpression(@javax.annotation.Nullable String applicabilityExpression) {
    this.applicabilityExpression = applicabilityExpression;
  }


  public SubmitRequirementInfo submittabilityExpression(@javax.annotation.Nullable String submittabilityExpression) {
    this.submittabilityExpression = submittabilityExpression;
    return this;
  }

  /**
   * Get submittabilityExpression
   * @return submittabilityExpression
   */
  @javax.annotation.Nullable
  public String getSubmittabilityExpression() {
    return submittabilityExpression;
  }

  public void setSubmittabilityExpression(@javax.annotation.Nullable String submittabilityExpression) {
    this.submittabilityExpression = submittabilityExpression;
  }


  public SubmitRequirementInfo overrideExpression(@javax.annotation.Nullable String overrideExpression) {
    this.overrideExpression = overrideExpression;
    return this;
  }

  /**
   * Get overrideExpression
   * @return overrideExpression
   */
  @javax.annotation.Nullable
  public String getOverrideExpression() {
    return overrideExpression;
  }

  public void setOverrideExpression(@javax.annotation.Nullable String overrideExpression) {
    this.overrideExpression = overrideExpression;
  }


  public SubmitRequirementInfo allowOverrideInChildProjects(@javax.annotation.Nullable Boolean allowOverrideInChildProjects) {
    this.allowOverrideInChildProjects = allowOverrideInChildProjects;
    return this;
  }

  /**
   * Get allowOverrideInChildProjects
   * @return allowOverrideInChildProjects
   */
  @javax.annotation.Nullable
  public Boolean getAllowOverrideInChildProjects() {
    return allowOverrideInChildProjects;
  }

  public void setAllowOverrideInChildProjects(@javax.annotation.Nullable Boolean allowOverrideInChildProjects) {
    this.allowOverrideInChildProjects = allowOverrideInChildProjects;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitRequirementInfo submitRequirementInfo = (SubmitRequirementInfo) o;
    return Objects.equals(this.name, submitRequirementInfo.name) &&
        Objects.equals(this.description, submitRequirementInfo.description) &&
        Objects.equals(this.projectName, submitRequirementInfo.projectName) &&
        Objects.equals(this.applicabilityExpression, submitRequirementInfo.applicabilityExpression) &&
        Objects.equals(this.submittabilityExpression, submitRequirementInfo.submittabilityExpression) &&
        Objects.equals(this.overrideExpression, submitRequirementInfo.overrideExpression) &&
        Objects.equals(this.allowOverrideInChildProjects, submitRequirementInfo.allowOverrideInChildProjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, projectName, applicabilityExpression, submittabilityExpression, overrideExpression, allowOverrideInChildProjects);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitRequirementInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    applicabilityExpression: ").append(toIndentedString(applicabilityExpression)).append("\n");
    sb.append("    submittabilityExpression: ").append(toIndentedString(submittabilityExpression)).append("\n");
    sb.append("    overrideExpression: ").append(toIndentedString(overrideExpression)).append("\n");
    sb.append("    allowOverrideInChildProjects: ").append(toIndentedString(allowOverrideInChildProjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "description", "project_name", "applicability_expression", "submittability_expression", "override_expression", "allow_override_in_child_projects"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubmitRequirementInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubmitRequirementInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SubmitRequirementInfo is not found in the empty JSON string", SubmitRequirementInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubmitRequirementInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SubmitRequirementInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("project_name") != null && !jsonObj.get("project_name").isJsonNull()) && !jsonObj.get("project_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `project_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("project_name").toString()));
      }
      if ((jsonObj.get("applicability_expression") != null && !jsonObj.get("applicability_expression").isJsonNull()) && !jsonObj.get("applicability_expression").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `applicability_expression` to be a primitive type in the JSON string but got `%s`", jsonObj.get("applicability_expression").toString()));
      }
      if ((jsonObj.get("submittability_expression") != null && !jsonObj.get("submittability_expression").isJsonNull()) && !jsonObj.get("submittability_expression").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `submittability_expression` to be a primitive type in the JSON string but got `%s`", jsonObj.get("submittability_expression").toString()));
      }
      if ((jsonObj.get("override_expression") != null && !jsonObj.get("override_expression").isJsonNull()) && !jsonObj.get("override_expression").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `override_expression` to be a primitive type in the JSON string but got `%s`", jsonObj.get("override_expression").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubmitRequirementInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubmitRequirementInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubmitRequirementInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubmitRequirementInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<SubmitRequirementInfo>() {
           @Override
           public void write(JsonWriter out, SubmitRequirementInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubmitRequirementInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubmitRequirementInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubmitRequirementInfo
   * @throws IOException if the JSON string is invalid with respect to SubmitRequirementInfo
   */
  public static SubmitRequirementInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubmitRequirementInfo.class);
  }

  /**
   * Convert an instance of SubmitRequirementInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

