/*
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.google.gerrit.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Whitespace
 */
@JsonAdapter(Whitespace.Adapter.class)
public enum Whitespace {
  
  IGNORE_NONE("IGNORE_NONE"),
  
  IGNORE_TRAILING("IGNORE_TRAILING"),
  
  IGNORE_LEADING_AND_TRAILING("IGNORE_LEADING_AND_TRAILING"),
  
  IGNORE_ALL("IGNORE_ALL");

  private String value;

  Whitespace(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Whitespace fromValue(String value) {
    for (Whitespace b : Whitespace.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Whitespace> {
    @Override
    public void write(final JsonWriter jsonWriter, final Whitespace enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Whitespace read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Whitespace.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    Whitespace.fromValue(value);
  }
}

